package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidMercAliauth;
import com.hq.sid.entity.generate.TSidMercAliauthExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidMercAliauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidMercAliauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidMercAliauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer coreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidMercAliauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidMercAliauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMercAliauth> selectByExampleWithRowbounds(TSidMercAliauthExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMercAliauth> selectByExample(TSidMercAliauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidMercAliauth selectByPrimaryKey(Integer coreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidMercAliauth record, @Param("example") TSidMercAliauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidMercAliauth record, @Param("example") TSidMercAliauthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidMercAliauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidMercAliauth record);
}