package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidOperConfig;
import com.hq.sid.entity.generate.TSidOperConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidOperConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidOperConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidOperConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidOperConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidOperConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidOperConfig> selectByExampleWithRowbounds(TSidOperConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidOperConfig> selectByExample(TSidOperConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidOperConfig selectByPrimaryKey(Integer operId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidOperConfig record, @Param("example") TSidOperConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidOperConfig record, @Param("example") TSidOperConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidOperConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper_config
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidOperConfig record);
}