package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidCore;
import com.hq.sid.entity.generate.TSidCoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidCore> selectByExampleWithRowbounds(TSidCoreExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidCore> selectByExample(TSidCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidCore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidCore record, @Param("example") TSidCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidCore record, @Param("example") TSidCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_core
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidCore record);
}