package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidOper;
import com.hq.sid.entity.generate.TSidOperExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidOperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidOper> selectByExampleWithRowbounds(TSidOperExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidOper> selectByExample(TSidOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidOper selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidOper record, @Param("example") TSidOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidOper record, @Param("example") TSidOperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidOper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidOper record);
}