package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidCodemould;
import com.hq.sid.entity.generate.TSidCodemouldExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidCodemouldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidCodemouldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidCodemouldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidCodemould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidCodemould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidCodemould> selectByExampleWithRowbounds(TSidCodemouldExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidCodemould> selectByExample(TSidCodemouldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidCodemould selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidCodemould record, @Param("example") TSidCodemouldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidCodemould record, @Param("example") TSidCodemouldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidCodemould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_codemould
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidCodemould record);
}