package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidDevice;
import com.hq.sid.entity.generate.TSidDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    long countByExample(TSidDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int deleteByExample(TSidDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int deleteByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int insert(TSidDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int insertSelective(TSidDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    List<TSidDevice> selectByExampleWithRowbounds(TSidDeviceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    List<TSidDevice> selectByExample(TSidDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    TSidDevice selectByPrimaryKey(String keyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidDevice record, @Param("example") TSidDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int updateByExample(@Param("record") TSidDevice record, @Param("example") TSidDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int updateByPrimaryKeySelective(TSidDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_device
     *
     * @mbg.generated Wed Feb 15 15:40:09 CST 2017
     */
    int updateByPrimaryKey(TSidDevice record);
}