package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidMercPic;
import com.hq.sid.entity.generate.TSidMercPicExample;
import com.hq.sid.entity.generate.TSidMercPicKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidMercPicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidMercPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidMercPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(TSidMercPicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidMercPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidMercPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMercPic> selectByExampleWithRowbounds(TSidMercPicExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMercPic> selectByExample(TSidMercPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidMercPic selectByPrimaryKey(TSidMercPicKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidMercPic record, @Param("example") TSidMercPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidMercPic record, @Param("example") TSidMercPicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidMercPic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_pic
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidMercPic record);
}