package com.hq.sid.dao.generate;

import com.hq.sid.entity.generate.TSidMerc;
import com.hq.sid.entity.generate.TSidMercExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSidMercMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    long countByExample(TSidMercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByExample(TSidMercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int deleteByPrimaryKey(Integer coreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insert(TSidMerc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int insertSelective(TSidMerc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMerc> selectByExampleWithRowbounds(TSidMercExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    List<TSidMerc> selectByExample(TSidMercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    TSidMerc selectByPrimaryKey(Integer coreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSidMerc record, @Param("example") TSidMercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByExample(@Param("record") TSidMerc record, @Param("example") TSidMercExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKeySelective(TSidMerc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    int updateByPrimaryKey(TSidMerc record);
}