package com.hq.flood.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class TFloodResource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.SYSTEM_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String systemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_NAME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_CODE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_TYPE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_DESC
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_STATUS
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_PARENT_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceParentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.RESOURCE_ORDER_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String resourceOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.LASTUPDATETIME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private Date lastupdatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_flood_resource.MODIFIED_USER
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private String modifiedUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_ID
     *
     * @return the value of t_flood_resource.RESOURCE_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_ID
     *
     * @param resourceId the value for t_flood_resource.RESOURCE_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceId(String resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.SYSTEM_ID
     *
     * @return the value of t_flood_resource.SYSTEM_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.SYSTEM_ID
     *
     * @param systemId the value for t_flood_resource.SYSTEM_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_NAME
     *
     * @return the value of t_flood_resource.RESOURCE_NAME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_NAME
     *
     * @param resourceName the value for t_flood_resource.RESOURCE_NAME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_CODE
     *
     * @return the value of t_flood_resource.RESOURCE_CODE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceCode() {
        return resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_CODE
     *
     * @param resourceCode the value for t_flood_resource.RESOURCE_CODE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceCode(String resourceCode) {
        this.resourceCode = resourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_TYPE
     *
     * @return the value of t_flood_resource.RESOURCE_TYPE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_TYPE
     *
     * @param resourceType the value for t_flood_resource.RESOURCE_TYPE
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_DESC
     *
     * @return the value of t_flood_resource.RESOURCE_DESC
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceDesc() {
        return resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_DESC
     *
     * @param resourceDesc the value for t_flood_resource.RESOURCE_DESC
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceDesc(String resourceDesc) {
        this.resourceDesc = resourceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_STATUS
     *
     * @return the value of t_flood_resource.RESOURCE_STATUS
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceStatus() {
        return resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_STATUS
     *
     * @param resourceStatus the value for t_flood_resource.RESOURCE_STATUS
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceStatus(String resourceStatus) {
        this.resourceStatus = resourceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_PARENT_ID
     *
     * @return the value of t_flood_resource.RESOURCE_PARENT_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceParentId() {
        return resourceParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_PARENT_ID
     *
     * @param resourceParentId the value for t_flood_resource.RESOURCE_PARENT_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceParentId(String resourceParentId) {
        this.resourceParentId = resourceParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.RESOURCE_ORDER_ID
     *
     * @return the value of t_flood_resource.RESOURCE_ORDER_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getResourceOrderId() {
        return resourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.RESOURCE_ORDER_ID
     *
     * @param resourceOrderId the value for t_flood_resource.RESOURCE_ORDER_ID
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setResourceOrderId(String resourceOrderId) {
        this.resourceOrderId = resourceOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.LASTUPDATETIME
     *
     * @return the value of t_flood_resource.LASTUPDATETIME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.LASTUPDATETIME
     *
     * @param lastupdatetime the value for t_flood_resource.LASTUPDATETIME
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_flood_resource.MODIFIED_USER
     *
     * @return the value of t_flood_resource.MODIFIED_USER
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public String getModifiedUser() {
        return modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_flood_resource.MODIFIED_USER
     *
     * @param modifiedUser the value for t_flood_resource.MODIFIED_USER
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    public void setModifiedUser(String modifiedUser) {
        this.modifiedUser = modifiedUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", resourceId=").append(resourceId);
        sb.append(", systemId=").append(systemId);
        sb.append(", resourceName=").append(resourceName);
        sb.append(", resourceCode=").append(resourceCode);
        sb.append(", resourceType=").append(resourceType);
        sb.append(", resourceDesc=").append(resourceDesc);
        sb.append(", resourceStatus=").append(resourceStatus);
        sb.append(", resourceParentId=").append(resourceParentId);
        sb.append(", resourceOrderId=").append(resourceOrderId);
        sb.append(", lastupdatetime=").append(lastupdatetime);
        sb.append(", modifiedUser=").append(modifiedUser);
        sb.append("]");
        return sb.toString();
    }
}