package com.hq.soto.dao.generate;

import com.hq.soto.entity.generate.TSotoFeeTemplate;
import com.hq.soto.entity.generate.TSotoFeeTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSotoFeeTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    long countByExample(TSotoFeeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int deleteByExample(TSotoFeeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insert(TSotoFeeTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insertSelective(TSotoFeeTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeTemplate> selectByExampleWithRowbounds(TSotoFeeTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeTemplate> selectByExample(TSotoFeeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    TSotoFeeTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSotoFeeTemplate record, @Param("example") TSotoFeeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExample(@Param("record") TSotoFeeTemplate record, @Param("example") TSotoFeeTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByPrimaryKeySelective(TSotoFeeTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByPrimaryKey(TSotoFeeTemplate record);
}