package com.hq.soto.dao.generate;

import com.hq.soto.entity.generate.TSotoFeeTemplateCore;
import com.hq.soto.entity.generate.TSotoFeeTemplateCoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSotoFeeTemplateCoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    long countByExample(TSotoFeeTemplateCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int deleteByExample(TSotoFeeTemplateCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insert(TSotoFeeTemplateCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insertSelective(TSotoFeeTemplateCore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeTemplateCore> selectByExampleWithRowbounds(TSotoFeeTemplateCoreExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeTemplateCore> selectByExample(TSotoFeeTemplateCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSotoFeeTemplateCore record, @Param("example") TSotoFeeTemplateCoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_template_core
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExample(@Param("record") TSotoFeeTemplateCore record, @Param("example") TSotoFeeTemplateCoreExample example);
}