package com.hq.soto.dao.generate;

import com.hq.soto.entity.generate.TSotoFeeInfo;
import com.hq.soto.entity.generate.TSotoFeeInfoExample;
import com.hq.soto.entity.generate.TSotoFeeInfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSotoFeeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    long countByExample(TSotoFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int deleteByExample(TSotoFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int deleteByPrimaryKey(TSotoFeeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insert(TSotoFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int insertSelective(TSotoFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeInfo> selectByExampleWithRowbounds(TSotoFeeInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    List<TSotoFeeInfo> selectByExample(TSotoFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    TSotoFeeInfo selectByPrimaryKey(TSotoFeeInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") TSotoFeeInfo record, @Param("example") TSotoFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByExample(@Param("record") TSotoFeeInfo record, @Param("example") TSotoFeeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByPrimaryKeySelective(TSotoFeeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    int updateByPrimaryKey(TSotoFeeInfo record);
}