package com.hq.soto.entity.generate;

import java.io.Serializable;

public class TSotoFeeInfoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_soto_fee_info.TEMPLATE_ID
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_soto_fee_info.PAY_TYPE
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_soto_fee_info.TEMPLATE_ID
     *
     * @return the value of t_soto_fee_info.TEMPLATE_ID
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_soto_fee_info.TEMPLATE_ID
     *
     * @param templateId the value for t_soto_fee_info.TEMPLATE_ID
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_soto_fee_info.PAY_TYPE
     *
     * @return the value of t_soto_fee_info.PAY_TYPE
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_soto_fee_info.PAY_TYPE
     *
     * @param payType the value for t_soto_fee_info.PAY_TYPE
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_soto_fee_info
     *
     * @mbg.generated Wed Mar 08 00:13:38 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateId=").append(templateId);
        sb.append(", payType=").append(payType);
        sb.append("]");
        return sb.toString();
    }
}