package com.hq.shira.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class TShiraConfHis implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.conf_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer confId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.tempt_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer temptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.agent_core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer agentCoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.start_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.end_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.tempt_name
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String temptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.tempt_desc
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String temptDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.tempt_status
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String temptStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.dist_unit
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer distUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.dist_type
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer distType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.fee_amt_fix
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer feeAmtFix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.dist_rate
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Float distRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.prd_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String prdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.crt_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String crtOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.crt_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.mdf_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private String mdfOperId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.mdf_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Date mdfTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer coreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shira_conf_his.is_universal
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private Integer isUniversal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.id
     *
     * @return the value of t_shira_conf_his.id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.id
     *
     * @param id the value for t_shira_conf_his.id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.conf_id
     *
     * @return the value of t_shira_conf_his.conf_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getConfId() {
        return confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.conf_id
     *
     * @param confId the value for t_shira_conf_his.conf_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setConfId(Integer confId) {
        this.confId = confId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.tempt_id
     *
     * @return the value of t_shira_conf_his.tempt_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getTemptId() {
        return temptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.tempt_id
     *
     * @param temptId the value for t_shira_conf_his.tempt_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setTemptId(Integer temptId) {
        this.temptId = temptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.agent_core_id
     *
     * @return the value of t_shira_conf_his.agent_core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getAgentCoreId() {
        return agentCoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.agent_core_id
     *
     * @param agentCoreId the value for t_shira_conf_his.agent_core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setAgentCoreId(Integer agentCoreId) {
        this.agentCoreId = agentCoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.start_time
     *
     * @return the value of t_shira_conf_his.start_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.start_time
     *
     * @param startTime the value for t_shira_conf_his.start_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.end_time
     *
     * @return the value of t_shira_conf_his.end_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.end_time
     *
     * @param endTime the value for t_shira_conf_his.end_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.tempt_name
     *
     * @return the value of t_shira_conf_his.tempt_name
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getTemptName() {
        return temptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.tempt_name
     *
     * @param temptName the value for t_shira_conf_his.tempt_name
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setTemptName(String temptName) {
        this.temptName = temptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.tempt_desc
     *
     * @return the value of t_shira_conf_his.tempt_desc
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getTemptDesc() {
        return temptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.tempt_desc
     *
     * @param temptDesc the value for t_shira_conf_his.tempt_desc
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setTemptDesc(String temptDesc) {
        this.temptDesc = temptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.tempt_status
     *
     * @return the value of t_shira_conf_his.tempt_status
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getTemptStatus() {
        return temptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.tempt_status
     *
     * @param temptStatus the value for t_shira_conf_his.tempt_status
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setTemptStatus(String temptStatus) {
        this.temptStatus = temptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.dist_unit
     *
     * @return the value of t_shira_conf_his.dist_unit
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getDistUnit() {
        return distUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.dist_unit
     *
     * @param distUnit the value for t_shira_conf_his.dist_unit
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setDistUnit(Integer distUnit) {
        this.distUnit = distUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.dist_type
     *
     * @return the value of t_shira_conf_his.dist_type
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getDistType() {
        return distType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.dist_type
     *
     * @param distType the value for t_shira_conf_his.dist_type
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setDistType(Integer distType) {
        this.distType = distType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.fee_amt_fix
     *
     * @return the value of t_shira_conf_his.fee_amt_fix
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getFeeAmtFix() {
        return feeAmtFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.fee_amt_fix
     *
     * @param feeAmtFix the value for t_shira_conf_his.fee_amt_fix
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setFeeAmtFix(Integer feeAmtFix) {
        this.feeAmtFix = feeAmtFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.dist_rate
     *
     * @return the value of t_shira_conf_his.dist_rate
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Float getDistRate() {
        return distRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.dist_rate
     *
     * @param distRate the value for t_shira_conf_his.dist_rate
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setDistRate(Float distRate) {
        this.distRate = distRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.prd_id
     *
     * @return the value of t_shira_conf_his.prd_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getPrdId() {
        return prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.prd_id
     *
     * @param prdId the value for t_shira_conf_his.prd_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setPrdId(String prdId) {
        this.prdId = prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.crt_oper_id
     *
     * @return the value of t_shira_conf_his.crt_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getCrtOperId() {
        return crtOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.crt_oper_id
     *
     * @param crtOperId the value for t_shira_conf_his.crt_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setCrtOperId(String crtOperId) {
        this.crtOperId = crtOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.crt_time
     *
     * @return the value of t_shira_conf_his.crt_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.crt_time
     *
     * @param crtTime the value for t_shira_conf_his.crt_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.mdf_oper_id
     *
     * @return the value of t_shira_conf_his.mdf_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public String getMdfOperId() {
        return mdfOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.mdf_oper_id
     *
     * @param mdfOperId the value for t_shira_conf_his.mdf_oper_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setMdfOperId(String mdfOperId) {
        this.mdfOperId = mdfOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.mdf_time
     *
     * @return the value of t_shira_conf_his.mdf_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Date getMdfTime() {
        return mdfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.mdf_time
     *
     * @param mdfTime the value for t_shira_conf_his.mdf_time
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setMdfTime(Date mdfTime) {
        this.mdfTime = mdfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.core_id
     *
     * @return the value of t_shira_conf_his.core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getCoreId() {
        return coreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.core_id
     *
     * @param coreId the value for t_shira_conf_his.core_id
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setCoreId(Integer coreId) {
        this.coreId = coreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shira_conf_his.is_universal
     *
     * @return the value of t_shira_conf_his.is_universal
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public Integer getIsUniversal() {
        return isUniversal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shira_conf_his.is_universal
     *
     * @param isUniversal the value for t_shira_conf_his.is_universal
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    public void setIsUniversal(Integer isUniversal) {
        this.isUniversal = isUniversal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", confId=").append(confId);
        sb.append(", temptId=").append(temptId);
        sb.append(", agentCoreId=").append(agentCoreId);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", temptName=").append(temptName);
        sb.append(", temptDesc=").append(temptDesc);
        sb.append(", temptStatus=").append(temptStatus);
        sb.append(", distUnit=").append(distUnit);
        sb.append(", distType=").append(distType);
        sb.append(", feeAmtFix=").append(feeAmtFix);
        sb.append(", distRate=").append(distRate);
        sb.append(", prdId=").append(prdId);
        sb.append(", crtOperId=").append(crtOperId);
        sb.append(", crtTime=").append(crtTime);
        sb.append(", mdfOperId=").append(mdfOperId);
        sb.append(", mdfTime=").append(mdfTime);
        sb.append(", coreId=").append(coreId);
        sb.append(", isUniversal=").append(isUniversal);
        sb.append("]");
        return sb.toString();
    }
}