package com.hq.diego.repository.dao.generate;

import com.hq.diego.repository.model.generate.TDiegoTradeOrder;
import com.hq.diego.repository.model.generate.TDiegoTradeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TDiegoTradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    long countByExample(TDiegoTradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int deleteByExample(TDiegoTradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int insert(TDiegoTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int insertSelective(TDiegoTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    List<TDiegoTradeOrder> selectByExampleWithRowbounds(TDiegoTradeOrderExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    List<TDiegoTradeOrder> selectByExample(TDiegoTradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    TDiegoTradeOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TDiegoTradeOrder record, @Param("example") TDiegoTradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByExample(@Param("record") TDiegoTradeOrder record, @Param("example") TDiegoTradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByPrimaryKeySelective(TDiegoTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_diego_trade_order
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByPrimaryKey(TDiegoTradeOrder record);
}