package com.hq.diego.repository.dao.generate;

import com.hq.diego.repository.model.generate.TRudyMchChannel;
import com.hq.diego.repository.model.generate.TRudyMchChannelExample;
import com.hq.diego.repository.model.generate.TRudyMchChannelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TRudyMchChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    long countByExample(TRudyMchChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int deleteByExample(TRudyMchChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int deleteByPrimaryKey(TRudyMchChannelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int insert(TRudyMchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int insertSelective(TRudyMchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    List<TRudyMchChannel> selectByExampleWithRowbounds(TRudyMchChannelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    List<TRudyMchChannel> selectByExample(TRudyMchChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    TRudyMchChannel selectByPrimaryKey(TRudyMchChannelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") TRudyMchChannel record, @Param("example") TRudyMchChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByExample(@Param("record") TRudyMchChannel record, @Param("example") TRudyMchChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByPrimaryKeySelective(TRudyMchChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_rudy_mch_channel
     *
     * @mbg.generated Wed Mar 22 18:29:43 CST 2017
     */
    int updateByPrimaryKey(TRudyMchChannel record);
}