package com.hq.elva.dao.generate;

import com.hq.elva.entity.generate.TBasBktype;
import com.hq.elva.entity.generate.TBasBktypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TBasBktypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int countByExample(TBasBktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int deleteByExample(TBasBktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int deleteByPrimaryKey(Integer bnkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int insert(TBasBktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int insertSelective(TBasBktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    List<TBasBktype> selectByExample(TBasBktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    TBasBktype selectByPrimaryKey(Integer bnkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasBktype record, @Param("example") TBasBktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int updateByExample(@Param("record") TBasBktype record, @Param("example") TBasBktypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int updateByPrimaryKeySelective(TBasBktype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bktyp
     *
     * @mbggenerated Thu Nov 03 15:15:42 CST 2016
     */
    int updateByPrimaryKey(TBasBktype record);
}