package com.hq.elva.dao.generate;

import com.hq.elva.entity.generate.TBasDict;
import com.hq.elva.entity.generate.TBasDictExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TBasDictMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int countByExample(TBasDictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int deleteByExample(TBasDictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int deleteByPrimaryKey(Long paramId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int insert(TBasDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int insertSelective(TBasDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	List<TBasDict> selectByExampleWithRowbounds(TBasDictExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	List<TBasDict> selectByExample(TBasDictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	TBasDict selectByPrimaryKey(Long paramId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TBasDict record, @Param("example") TBasDictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByExample(@Param("record") TBasDict record, @Param("example") TBasDictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByPrimaryKeySelective(TBasDict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_dict
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByPrimaryKey(TBasDict record);
}