package com.hq.elva.dao.generate;

import com.hq.elva.entity.generate.TBasConfig;
import com.hq.elva.entity.generate.TBasConfigExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TBasConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int countByExample(TBasConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int deleteByExample(TBasConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int deleteByPrimaryKey(Long configId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int insert(TBasConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int insertSelective(TBasConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	List<TBasConfig> selectByExampleWithRowbounds(TBasConfigExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	List<TBasConfig> selectByExample(TBasConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	TBasConfig selectByPrimaryKey(Long configId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByExampleSelective(@Param("record") TBasConfig record, @Param("example") TBasConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByExample(@Param("record") TBasConfig record, @Param("example") TBasConfigExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByPrimaryKeySelective(TBasConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	int updateByPrimaryKey(TBasConfig record);
}