package com.hq.elva.dao.generate;

import com.hq.elva.entity.generate.TBasMcc;
import com.hq.elva.entity.generate.TBasMccExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TBasMccMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int countByExample(TBasMccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int deleteByExample(TBasMccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int deleteByPrimaryKey(String mccCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int insert(TBasMcc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int insertSelective(TBasMcc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    List<TBasMcc> selectByExample(TBasMccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    TBasMcc selectByPrimaryKey(String mccCd);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int updateByExampleSelective(@Param("record") TBasMcc record, @Param("example") TBasMccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int updateByExample(@Param("record") TBasMcc record, @Param("example") TBasMccExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int updateByPrimaryKeySelective(TBasMcc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_mcc
     *
     * @mbggenerated Tue Nov 08 11:47:50 CST 2016
     */
    int updateByPrimaryKey(TBasMcc record);
}