package com.hq.shira.dao.generate;

import com.hq.shira.entity.generate.TShiraProfitDetail;
import com.hq.shira.entity.generate.TShiraProfitDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TShiraProfitDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    long countByExample(TShiraProfitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByExample(TShiraProfitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insert(TShiraProfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insertSelective(TShiraProfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraProfitDetail> selectByExampleWithRowbounds(TShiraProfitDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraProfitDetail> selectByExample(TShiraProfitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    TShiraProfitDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TShiraProfitDetail record, @Param("example") TShiraProfitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExample(@Param("record") TShiraProfitDetail record, @Param("example") TShiraProfitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKeySelective(TShiraProfitDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_detail
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKey(TShiraProfitDetail record);
}