package com.hq.shira.dao.generate;

import com.hq.shira.entity.generate.TShiraProfitSettle;
import com.hq.shira.entity.generate.TShiraProfitSettleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TShiraProfitSettleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    long countByExample(TShiraProfitSettleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByExample(TShiraProfitSettleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insert(TShiraProfitSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insertSelective(TShiraProfitSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraProfitSettle> selectByExampleWithRowbounds(TShiraProfitSettleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraProfitSettle> selectByExample(TShiraProfitSettleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    TShiraProfitSettle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TShiraProfitSettle record, @Param("example") TShiraProfitSettleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExample(@Param("record") TShiraProfitSettle record, @Param("example") TShiraProfitSettleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKeySelective(TShiraProfitSettle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_profit_settle
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKey(TShiraProfitSettle record);
}