package com.hq.shira.dao.generate;

import com.hq.shira.entity.generate.TShiraConfHis;
import com.hq.shira.entity.generate.TShiraConfHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TShiraConfHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    long countByExample(TShiraConfHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByExample(TShiraConfHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insert(TShiraConfHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insertSelective(TShiraConfHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraConfHis> selectByExampleWithRowbounds(TShiraConfHisExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraConfHis> selectByExample(TShiraConfHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    TShiraConfHis selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TShiraConfHis record, @Param("example") TShiraConfHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExample(@Param("record") TShiraConfHis record, @Param("example") TShiraConfHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKeySelective(TShiraConfHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf_his
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKey(TShiraConfHis record);
}