package com.hq.shira.dao.generate;

import com.hq.shira.entity.generate.TShiraConf;
import com.hq.shira.entity.generate.TShiraConfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TShiraConfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    long countByExample(TShiraConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByExample(TShiraConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insert(TShiraConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int insertSelective(TShiraConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraConf> selectByExampleWithRowbounds(TShiraConfExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    List<TShiraConf> selectByExample(TShiraConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    TShiraConf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExampleSelective(@Param("record") TShiraConf record, @Param("example") TShiraConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByExample(@Param("record") TShiraConf record, @Param("example") TShiraConfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKeySelective(TShiraConf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shira_conf
     *
     * @mbg.generated Wed Apr 05 23:04:28 CST 2017
     */
    int updateByPrimaryKey(TShiraConf record);
}