package com.hq.sid.entity.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSidOperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public TSidOperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdIsNull() {
            addCriterion("BELONE_CORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdIsNotNull() {
            addCriterion("BELONE_CORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdEqualTo(Integer value) {
            addCriterion("BELONE_CORE_ID =", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdNotEqualTo(Integer value) {
            addCriterion("BELONE_CORE_ID <>", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdGreaterThan(Integer value) {
            addCriterion("BELONE_CORE_ID >", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BELONE_CORE_ID >=", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdLessThan(Integer value) {
            addCriterion("BELONE_CORE_ID <", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("BELONE_CORE_ID <=", value, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdIn(List<Integer> values) {
            addCriterion("BELONE_CORE_ID in", values, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdNotIn(List<Integer> values) {
            addCriterion("BELONE_CORE_ID not in", values, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdBetween(Integer value1, Integer value2) {
            addCriterion("BELONE_CORE_ID between", value1, value2, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andBeloneCoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BELONE_CORE_ID not between", value1, value2, "beloneCoreId");
            return (Criteria) this;
        }

        public Criteria andOperNameIsNull() {
            addCriterion("OPER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOperNameIsNotNull() {
            addCriterion("OPER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOperNameEqualTo(String value) {
            addCriterion("OPER_NAME =", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotEqualTo(String value) {
            addCriterion("OPER_NAME <>", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameGreaterThan(String value) {
            addCriterion("OPER_NAME >", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_NAME >=", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLessThan(String value) {
            addCriterion("OPER_NAME <", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLessThanOrEqualTo(String value) {
            addCriterion("OPER_NAME <=", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameLike(String value) {
            addCriterion("OPER_NAME like", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotLike(String value) {
            addCriterion("OPER_NAME not like", value, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameIn(List<String> values) {
            addCriterion("OPER_NAME in", values, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotIn(List<String> values) {
            addCriterion("OPER_NAME not in", values, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameBetween(String value1, String value2) {
            addCriterion("OPER_NAME between", value1, value2, "operName");
            return (Criteria) this;
        }

        public Criteria andOperNameNotBetween(String value1, String value2) {
            addCriterion("OPER_NAME not between", value1, value2, "operName");
            return (Criteria) this;
        }

        public Criteria andOperAliasIsNull() {
            addCriterion("OPER_ALIAS is null");
            return (Criteria) this;
        }

        public Criteria andOperAliasIsNotNull() {
            addCriterion("OPER_ALIAS is not null");
            return (Criteria) this;
        }

        public Criteria andOperAliasEqualTo(String value) {
            addCriterion("OPER_ALIAS =", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasNotEqualTo(String value) {
            addCriterion("OPER_ALIAS <>", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasGreaterThan(String value) {
            addCriterion("OPER_ALIAS >", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_ALIAS >=", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasLessThan(String value) {
            addCriterion("OPER_ALIAS <", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasLessThanOrEqualTo(String value) {
            addCriterion("OPER_ALIAS <=", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasLike(String value) {
            addCriterion("OPER_ALIAS like", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasNotLike(String value) {
            addCriterion("OPER_ALIAS not like", value, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasIn(List<String> values) {
            addCriterion("OPER_ALIAS in", values, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasNotIn(List<String> values) {
            addCriterion("OPER_ALIAS not in", values, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasBetween(String value1, String value2) {
            addCriterion("OPER_ALIAS between", value1, value2, "operAlias");
            return (Criteria) this;
        }

        public Criteria andOperAliasNotBetween(String value1, String value2) {
            addCriterion("OPER_ALIAS not between", value1, value2, "operAlias");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNull() {
            addCriterion("MOBILE_PHONE is null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIsNotNull() {
            addCriterion("MOBILE_PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneEqualTo(String value) {
            addCriterion("MOBILE_PHONE =", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotEqualTo(String value) {
            addCriterion("MOBILE_PHONE <>", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThan(String value) {
            addCriterion("MOBILE_PHONE >", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE >=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThan(String value) {
            addCriterion("MOBILE_PHONE <", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("MOBILE_PHONE <=", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneLike(String value) {
            addCriterion("MOBILE_PHONE like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotLike(String value) {
            addCriterion("MOBILE_PHONE not like", value, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneIn(List<String> values) {
            addCriterion("MOBILE_PHONE in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotIn(List<String> values) {
            addCriterion("MOBILE_PHONE not in", values, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("MOBILE_PHONE not between", value1, value2, "mobilePhone");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNull() {
            addCriterion("LOGIN_ID is null");
            return (Criteria) this;
        }

        public Criteria andLoginIdIsNotNull() {
            addCriterion("LOGIN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLoginIdEqualTo(String value) {
            addCriterion("LOGIN_ID =", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotEqualTo(String value) {
            addCriterion("LOGIN_ID <>", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThan(String value) {
            addCriterion("LOGIN_ID >", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdGreaterThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID >=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThan(String value) {
            addCriterion("LOGIN_ID <", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLessThanOrEqualTo(String value) {
            addCriterion("LOGIN_ID <=", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdLike(String value) {
            addCriterion("LOGIN_ID like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotLike(String value) {
            addCriterion("LOGIN_ID not like", value, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdIn(List<String> values) {
            addCriterion("LOGIN_ID in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotIn(List<String> values) {
            addCriterion("LOGIN_ID not in", values, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdBetween(String value1, String value2) {
            addCriterion("LOGIN_ID between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andLoginIdNotBetween(String value1, String value2) {
            addCriterion("LOGIN_ID not between", value1, value2, "loginId");
            return (Criteria) this;
        }

        public Criteria andOperPwdIsNull() {
            addCriterion("OPER_PWD is null");
            return (Criteria) this;
        }

        public Criteria andOperPwdIsNotNull() {
            addCriterion("OPER_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andOperPwdEqualTo(String value) {
            addCriterion("OPER_PWD =", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdNotEqualTo(String value) {
            addCriterion("OPER_PWD <>", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdGreaterThan(String value) {
            addCriterion("OPER_PWD >", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdGreaterThanOrEqualTo(String value) {
            addCriterion("OPER_PWD >=", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdLessThan(String value) {
            addCriterion("OPER_PWD <", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdLessThanOrEqualTo(String value) {
            addCriterion("OPER_PWD <=", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdLike(String value) {
            addCriterion("OPER_PWD like", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdNotLike(String value) {
            addCriterion("OPER_PWD not like", value, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdIn(List<String> values) {
            addCriterion("OPER_PWD in", values, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdNotIn(List<String> values) {
            addCriterion("OPER_PWD not in", values, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdBetween(String value1, String value2) {
            addCriterion("OPER_PWD between", value1, value2, "operPwd");
            return (Criteria) this;
        }

        public Criteria andOperPwdNotBetween(String value1, String value2) {
            addCriterion("OPER_PWD not between", value1, value2, "operPwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdIsNull() {
            addCriterion("NEED_CHANGE_PWD is null");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdIsNotNull() {
            addCriterion("NEED_CHANGE_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdEqualTo(Boolean value) {
            addCriterion("NEED_CHANGE_PWD =", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdNotEqualTo(Boolean value) {
            addCriterion("NEED_CHANGE_PWD <>", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdGreaterThan(Boolean value) {
            addCriterion("NEED_CHANGE_PWD >", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdGreaterThanOrEqualTo(Boolean value) {
            addCriterion("NEED_CHANGE_PWD >=", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdLessThan(Boolean value) {
            addCriterion("NEED_CHANGE_PWD <", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdLessThanOrEqualTo(Boolean value) {
            addCriterion("NEED_CHANGE_PWD <=", value, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdIn(List<Boolean> values) {
            addCriterion("NEED_CHANGE_PWD in", values, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdNotIn(List<Boolean> values) {
            addCriterion("NEED_CHANGE_PWD not in", values, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdBetween(Boolean value1, Boolean value2) {
            addCriterion("NEED_CHANGE_PWD between", value1, value2, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andNeedChangePwdNotBetween(Boolean value1, Boolean value2) {
            addCriterion("NEED_CHANGE_PWD not between", value1, value2, "needChangePwd");
            return (Criteria) this;
        }

        public Criteria andIsAdminIsNull() {
            addCriterion("IS_ADMIN is null");
            return (Criteria) this;
        }

        public Criteria andIsAdminIsNotNull() {
            addCriterion("IS_ADMIN is not null");
            return (Criteria) this;
        }

        public Criteria andIsAdminEqualTo(Boolean value) {
            addCriterion("IS_ADMIN =", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminNotEqualTo(Boolean value) {
            addCriterion("IS_ADMIN <>", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminGreaterThan(Boolean value) {
            addCriterion("IS_ADMIN >", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IS_ADMIN >=", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminLessThan(Boolean value) {
            addCriterion("IS_ADMIN <", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminLessThanOrEqualTo(Boolean value) {
            addCriterion("IS_ADMIN <=", value, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminIn(List<Boolean> values) {
            addCriterion("IS_ADMIN in", values, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminNotIn(List<Boolean> values) {
            addCriterion("IS_ADMIN not in", values, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ADMIN between", value1, value2, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andIsAdminNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IS_ADMIN not between", value1, value2, "isAdmin");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNull() {
            addCriterion("LOGIN_TIME is null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIsNotNull() {
            addCriterion("LOGIN_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andLoginTimeEqualTo(Date value) {
            addCriterion("LOGIN_TIME =", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotEqualTo(Date value) {
            addCriterion("LOGIN_TIME <>", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThan(Date value) {
            addCriterion("LOGIN_TIME >", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LOGIN_TIME >=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThan(Date value) {
            addCriterion("LOGIN_TIME <", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeLessThanOrEqualTo(Date value) {
            addCriterion("LOGIN_TIME <=", value, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeIn(List<Date> values) {
            addCriterion("LOGIN_TIME in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotIn(List<Date> values) {
            addCriterion("LOGIN_TIME not in", values, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeBetween(Date value1, Date value2) {
            addCriterion("LOGIN_TIME between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andLoginTimeNotBetween(Date value1, Date value2) {
            addCriterion("LOGIN_TIME not between", value1, value2, "loginTime");
            return (Criteria) this;
        }

        public Criteria andFailCntIsNull() {
            addCriterion("FAIL_CNT is null");
            return (Criteria) this;
        }

        public Criteria andFailCntIsNotNull() {
            addCriterion("FAIL_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andFailCntEqualTo(Integer value) {
            addCriterion("FAIL_CNT =", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntNotEqualTo(Integer value) {
            addCriterion("FAIL_CNT <>", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntGreaterThan(Integer value) {
            addCriterion("FAIL_CNT >", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntGreaterThanOrEqualTo(Integer value) {
            addCriterion("FAIL_CNT >=", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntLessThan(Integer value) {
            addCriterion("FAIL_CNT <", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntLessThanOrEqualTo(Integer value) {
            addCriterion("FAIL_CNT <=", value, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntIn(List<Integer> values) {
            addCriterion("FAIL_CNT in", values, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntNotIn(List<Integer> values) {
            addCriterion("FAIL_CNT not in", values, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntBetween(Integer value1, Integer value2) {
            addCriterion("FAIL_CNT between", value1, value2, "failCnt");
            return (Criteria) this;
        }

        public Criteria andFailCntNotBetween(Integer value1, Integer value2) {
            addCriterion("FAIL_CNT not between", value1, value2, "failCnt");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIsNull() {
            addCriterion("CRT_OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIsNotNull() {
            addCriterion("CRT_OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdEqualTo(Integer value) {
            addCriterion("CRT_OPER_ID =", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotEqualTo(Integer value) {
            addCriterion("CRT_OPER_ID <>", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdGreaterThan(Integer value) {
            addCriterion("CRT_OPER_ID >", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CRT_OPER_ID >=", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdLessThan(Integer value) {
            addCriterion("CRT_OPER_ID <", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdLessThanOrEqualTo(Integer value) {
            addCriterion("CRT_OPER_ID <=", value, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdIn(List<Integer> values) {
            addCriterion("CRT_OPER_ID in", values, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotIn(List<Integer> values) {
            addCriterion("CRT_OPER_ID not in", values, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdBetween(Integer value1, Integer value2) {
            addCriterion("CRT_OPER_ID between", value1, value2, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtOperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CRT_OPER_ID not between", value1, value2, "crtOperId");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("CRT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("CRT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(Date value) {
            addCriterion("CRT_TIME =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(Date value) {
            addCriterion("CRT_TIME <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(Date value) {
            addCriterion("CRT_TIME >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(Date value) {
            addCriterion("CRT_TIME <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(Date value) {
            addCriterion("CRT_TIME <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<Date> values) {
            addCriterion("CRT_TIME in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<Date> values) {
            addCriterion("CRT_TIME not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(Date value1, Date value2) {
            addCriterion("CRT_TIME not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdIsNull() {
            addCriterion("MDF_OPER_ID is null");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdIsNotNull() {
            addCriterion("MDF_OPER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdEqualTo(Integer value) {
            addCriterion("MDF_OPER_ID =", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdNotEqualTo(Integer value) {
            addCriterion("MDF_OPER_ID <>", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdGreaterThan(Integer value) {
            addCriterion("MDF_OPER_ID >", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MDF_OPER_ID >=", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdLessThan(Integer value) {
            addCriterion("MDF_OPER_ID <", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdLessThanOrEqualTo(Integer value) {
            addCriterion("MDF_OPER_ID <=", value, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdIn(List<Integer> values) {
            addCriterion("MDF_OPER_ID in", values, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdNotIn(List<Integer> values) {
            addCriterion("MDF_OPER_ID not in", values, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdBetween(Integer value1, Integer value2) {
            addCriterion("MDF_OPER_ID between", value1, value2, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfOperIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MDF_OPER_ID not between", value1, value2, "mdfOperId");
            return (Criteria) this;
        }

        public Criteria andMdfTimeIsNull() {
            addCriterion("MDF_TIME is null");
            return (Criteria) this;
        }

        public Criteria andMdfTimeIsNotNull() {
            addCriterion("MDF_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andMdfTimeEqualTo(Date value) {
            addCriterion("MDF_TIME =", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeNotEqualTo(Date value) {
            addCriterion("MDF_TIME <>", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeGreaterThan(Date value) {
            addCriterion("MDF_TIME >", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MDF_TIME >=", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeLessThan(Date value) {
            addCriterion("MDF_TIME <", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeLessThanOrEqualTo(Date value) {
            addCriterion("MDF_TIME <=", value, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeIn(List<Date> values) {
            addCriterion("MDF_TIME in", values, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeNotIn(List<Date> values) {
            addCriterion("MDF_TIME not in", values, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeBetween(Date value1, Date value2) {
            addCriterion("MDF_TIME between", value1, value2, "mdfTime");
            return (Criteria) this;
        }

        public Criteria andMdfTimeNotBetween(Date value1, Date value2) {
            addCriterion("MDF_TIME not between", value1, value2, "mdfTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_oper
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 21 20:05:58 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_oper
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}