package com.hq.sid.entity.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TSidMercAliauthExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public TSidMercAliauthExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCoreIdIsNull() {
            addCriterion("CORE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCoreIdIsNotNull() {
            addCriterion("CORE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCoreIdEqualTo(Integer value) {
            addCriterion("CORE_ID =", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdNotEqualTo(Integer value) {
            addCriterion("CORE_ID <>", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdGreaterThan(Integer value) {
            addCriterion("CORE_ID >", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CORE_ID >=", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdLessThan(Integer value) {
            addCriterion("CORE_ID <", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdLessThanOrEqualTo(Integer value) {
            addCriterion("CORE_ID <=", value, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdIn(List<Integer> values) {
            addCriterion("CORE_ID in", values, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdNotIn(List<Integer> values) {
            addCriterion("CORE_ID not in", values, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdBetween(Integer value1, Integer value2) {
            addCriterion("CORE_ID between", value1, value2, "coreId");
            return (Criteria) this;
        }

        public Criteria andCoreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CORE_ID not between", value1, value2, "coreId");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenIsNull() {
            addCriterion("APP_AUTH_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenIsNotNull() {
            addCriterion("APP_AUTH_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenEqualTo(String value) {
            addCriterion("APP_AUTH_TOKEN =", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenNotEqualTo(String value) {
            addCriterion("APP_AUTH_TOKEN <>", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenGreaterThan(String value) {
            addCriterion("APP_AUTH_TOKEN >", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenGreaterThanOrEqualTo(String value) {
            addCriterion("APP_AUTH_TOKEN >=", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenLessThan(String value) {
            addCriterion("APP_AUTH_TOKEN <", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenLessThanOrEqualTo(String value) {
            addCriterion("APP_AUTH_TOKEN <=", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenLike(String value) {
            addCriterion("APP_AUTH_TOKEN like", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenNotLike(String value) {
            addCriterion("APP_AUTH_TOKEN not like", value, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenIn(List<String> values) {
            addCriterion("APP_AUTH_TOKEN in", values, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenNotIn(List<String> values) {
            addCriterion("APP_AUTH_TOKEN not in", values, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenBetween(String value1, String value2) {
            addCriterion("APP_AUTH_TOKEN between", value1, value2, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andAppAuthTokenNotBetween(String value1, String value2) {
            addCriterion("APP_AUTH_TOKEN not between", value1, value2, "appAuthToken");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenIsNull() {
            addCriterion("APP_REFRESH_TOKEN is null");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenIsNotNull() {
            addCriterion("APP_REFRESH_TOKEN is not null");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenEqualTo(String value) {
            addCriterion("APP_REFRESH_TOKEN =", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenNotEqualTo(String value) {
            addCriterion("APP_REFRESH_TOKEN <>", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenGreaterThan(String value) {
            addCriterion("APP_REFRESH_TOKEN >", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("APP_REFRESH_TOKEN >=", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenLessThan(String value) {
            addCriterion("APP_REFRESH_TOKEN <", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("APP_REFRESH_TOKEN <=", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenLike(String value) {
            addCriterion("APP_REFRESH_TOKEN like", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenNotLike(String value) {
            addCriterion("APP_REFRESH_TOKEN not like", value, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenIn(List<String> values) {
            addCriterion("APP_REFRESH_TOKEN in", values, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenNotIn(List<String> values) {
            addCriterion("APP_REFRESH_TOKEN not in", values, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenBetween(String value1, String value2) {
            addCriterion("APP_REFRESH_TOKEN between", value1, value2, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAppRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("APP_REFRESH_TOKEN not between", value1, value2, "appRefreshToken");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdIsNull() {
            addCriterion("AUTH_APP_ID is null");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdIsNotNull() {
            addCriterion("AUTH_APP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdEqualTo(String value) {
            addCriterion("AUTH_APP_ID =", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdNotEqualTo(String value) {
            addCriterion("AUTH_APP_ID <>", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdGreaterThan(String value) {
            addCriterion("AUTH_APP_ID >", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("AUTH_APP_ID >=", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdLessThan(String value) {
            addCriterion("AUTH_APP_ID <", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdLessThanOrEqualTo(String value) {
            addCriterion("AUTH_APP_ID <=", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdLike(String value) {
            addCriterion("AUTH_APP_ID like", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdNotLike(String value) {
            addCriterion("AUTH_APP_ID not like", value, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdIn(List<String> values) {
            addCriterion("AUTH_APP_ID in", values, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdNotIn(List<String> values) {
            addCriterion("AUTH_APP_ID not in", values, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdBetween(String value1, String value2) {
            addCriterion("AUTH_APP_ID between", value1, value2, "authAppId");
            return (Criteria) this;
        }

        public Criteria andAuthAppIdNotBetween(String value1, String value2) {
            addCriterion("AUTH_APP_ID not between", value1, value2, "authAppId");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNull() {
            addCriterion("EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andExpDateIsNotNull() {
            addCriterion("EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andExpDateEqualTo(Date value) {
            addCriterion("EXP_DATE =", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotEqualTo(Date value) {
            addCriterion("EXP_DATE <>", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThan(Date value) {
            addCriterion("EXP_DATE >", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE >=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThan(Date value) {
            addCriterion("EXP_DATE <", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateLessThanOrEqualTo(Date value) {
            addCriterion("EXP_DATE <=", value, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateIn(List<Date> values) {
            addCriterion("EXP_DATE in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotIn(List<Date> values) {
            addCriterion("EXP_DATE not in", values, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andExpDateNotBetween(Date value1, Date value2) {
            addCriterion("EXP_DATE not between", value1, value2, "expDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateIsNull() {
            addCriterion("RE_EXP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andReExpDateIsNotNull() {
            addCriterion("RE_EXP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andReExpDateEqualTo(Date value) {
            addCriterion("RE_EXP_DATE =", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateNotEqualTo(Date value) {
            addCriterion("RE_EXP_DATE <>", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateGreaterThan(Date value) {
            addCriterion("RE_EXP_DATE >", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateGreaterThanOrEqualTo(Date value) {
            addCriterion("RE_EXP_DATE >=", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateLessThan(Date value) {
            addCriterion("RE_EXP_DATE <", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateLessThanOrEqualTo(Date value) {
            addCriterion("RE_EXP_DATE <=", value, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateIn(List<Date> values) {
            addCriterion("RE_EXP_DATE in", values, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateNotIn(List<Date> values) {
            addCriterion("RE_EXP_DATE not in", values, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateBetween(Date value1, Date value2) {
            addCriterion("RE_EXP_DATE between", value1, value2, "reExpDate");
            return (Criteria) this;
        }

        public Criteria andReExpDateNotBetween(Date value1, Date value2) {
            addCriterion("RE_EXP_DATE not between", value1, value2, "reExpDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated do_not_delete_during_merge Tue Feb 21 20:05:58 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sid_merc_aliauth
     *
     * @mbg.generated Tue Feb 21 20:05:58 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}