package com.hq.tony.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class WeixinCmsStyle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.REVIEW_IMG_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String reviewImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.TEMPLATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.TEMPLATE_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String templateUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_style.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.ID
     *
     * @return the value of weixin_cms_style.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.ID
     *
     * @param id the value for weixin_cms_style.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.ACCOUNTID
     *
     * @return the value of weixin_cms_style.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.ACCOUNTID
     *
     * @param accountid the value for weixin_cms_style.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.CREATE_DATE
     *
     * @return the value of weixin_cms_style.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.CREATE_DATE
     *
     * @param createDate the value for weixin_cms_style.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.CREATE_NAME
     *
     * @return the value of weixin_cms_style.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.CREATE_NAME
     *
     * @param createName the value for weixin_cms_style.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.REVIEW_IMG_URL
     *
     * @return the value of weixin_cms_style.REVIEW_IMG_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getReviewImgUrl() {
        return reviewImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.REVIEW_IMG_URL
     *
     * @param reviewImgUrl the value for weixin_cms_style.REVIEW_IMG_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setReviewImgUrl(String reviewImgUrl) {
        this.reviewImgUrl = reviewImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.TEMPLATE_NAME
     *
     * @return the value of weixin_cms_style.TEMPLATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.TEMPLATE_NAME
     *
     * @param templateName the value for weixin_cms_style.TEMPLATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.TEMPLATE_URL
     *
     * @return the value of weixin_cms_style.TEMPLATE_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getTemplateUrl() {
        return templateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.TEMPLATE_URL
     *
     * @param templateUrl the value for weixin_cms_style.TEMPLATE_URL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setTemplateUrl(String templateUrl) {
        this.templateUrl = templateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.UPDATE_DATE
     *
     * @return the value of weixin_cms_style.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.UPDATE_DATE
     *
     * @param updateDate the value for weixin_cms_style.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_style.UPDATE_NAME
     *
     * @return the value of weixin_cms_style.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_style.UPDATE_NAME
     *
     * @param updateName the value for weixin_cms_style.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountid=").append(accountid);
        sb.append(", createDate=").append(createDate);
        sb.append(", createName=").append(createName);
        sb.append(", reviewImgUrl=").append(reviewImgUrl);
        sb.append(", templateName=").append(templateName);
        sb.append(", templateUrl=").append(templateUrl);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateName=").append(updateName);
        sb.append("]");
        return sb.toString();
    }
}