package com.hq.tony.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class WeixinLinksucai implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.id
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.create_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.create_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.update_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String updateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.update_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.transfer_sign
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Integer transferSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.accountid
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.post_code
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String postCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.share_status
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String shareStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_linksucai.is_encrypt
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Integer isEncrypt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.id
     *
     * @return the value of weixin_linksucai.id
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.id
     *
     * @param id the value for weixin_linksucai.id
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.create_name
     *
     * @return the value of weixin_linksucai.create_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.create_name
     *
     * @param createName the value for weixin_linksucai.create_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.create_date
     *
     * @return the value of weixin_linksucai.create_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.create_date
     *
     * @param createDate the value for weixin_linksucai.create_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.update_name
     *
     * @return the value of weixin_linksucai.update_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.update_name
     *
     * @param updateName the value for weixin_linksucai.update_name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.update_date
     *
     * @return the value of weixin_linksucai.update_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.update_date
     *
     * @param updateDate the value for weixin_linksucai.update_date
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.name
     *
     * @return the value of weixin_linksucai.name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.name
     *
     * @param name the value for weixin_linksucai.name
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.transfer_sign
     *
     * @return the value of weixin_linksucai.transfer_sign
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Integer getTransferSign() {
        return transferSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.transfer_sign
     *
     * @param transferSign the value for weixin_linksucai.transfer_sign
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setTransferSign(Integer transferSign) {
        this.transferSign = transferSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.accountid
     *
     * @return the value of weixin_linksucai.accountid
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.accountid
     *
     * @param accountid the value for weixin_linksucai.accountid
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.post_code
     *
     * @return the value of weixin_linksucai.post_code
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.post_code
     *
     * @param postCode the value for weixin_linksucai.post_code
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.share_status
     *
     * @return the value of weixin_linksucai.share_status
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getShareStatus() {
        return shareStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.share_status
     *
     * @param shareStatus the value for weixin_linksucai.share_status
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setShareStatus(String shareStatus) {
        this.shareStatus = shareStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_linksucai.is_encrypt
     *
     * @return the value of weixin_linksucai.is_encrypt
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Integer getIsEncrypt() {
        return isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_linksucai.is_encrypt
     *
     * @param isEncrypt the value for weixin_linksucai.is_encrypt
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setIsEncrypt(Integer isEncrypt) {
        this.isEncrypt = isEncrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", createName=").append(createName);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateName=").append(updateName);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", name=").append(name);
        sb.append(", transferSign=").append(transferSign);
        sb.append(", accountid=").append(accountid);
        sb.append(", postCode=").append(postCode);
        sb.append(", shareStatus=").append(shareStatus);
        sb.append(", isEncrypt=").append(isEncrypt);
        sb.append("]");
        return sb.toString();
    }
}