package com.hq.tony.entity.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WeixinAccountExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public WeixinAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNull() {
            addCriterion("accountname is null");
            return (Criteria) this;
        }

        public Criteria andAccountnameIsNotNull() {
            addCriterion("accountname is not null");
            return (Criteria) this;
        }

        public Criteria andAccountnameEqualTo(String value) {
            addCriterion("accountname =", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotEqualTo(String value) {
            addCriterion("accountname <>", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThan(String value) {
            addCriterion("accountname >", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameGreaterThanOrEqualTo(String value) {
            addCriterion("accountname >=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThan(String value) {
            addCriterion("accountname <", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLessThanOrEqualTo(String value) {
            addCriterion("accountname <=", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameLike(String value) {
            addCriterion("accountname like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotLike(String value) {
            addCriterion("accountname not like", value, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameIn(List<String> values) {
            addCriterion("accountname in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotIn(List<String> values) {
            addCriterion("accountname not in", values, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameBetween(String value1, String value2) {
            addCriterion("accountname between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccountnameNotBetween(String value1, String value2) {
            addCriterion("accountname not between", value1, value2, "accountname");
            return (Criteria) this;
        }

        public Criteria andAccounttokenIsNull() {
            addCriterion("accounttoken is null");
            return (Criteria) this;
        }

        public Criteria andAccounttokenIsNotNull() {
            addCriterion("accounttoken is not null");
            return (Criteria) this;
        }

        public Criteria andAccounttokenEqualTo(String value) {
            addCriterion("accounttoken =", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenNotEqualTo(String value) {
            addCriterion("accounttoken <>", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenGreaterThan(String value) {
            addCriterion("accounttoken >", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenGreaterThanOrEqualTo(String value) {
            addCriterion("accounttoken >=", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenLessThan(String value) {
            addCriterion("accounttoken <", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenLessThanOrEqualTo(String value) {
            addCriterion("accounttoken <=", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenLike(String value) {
            addCriterion("accounttoken like", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenNotLike(String value) {
            addCriterion("accounttoken not like", value, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenIn(List<String> values) {
            addCriterion("accounttoken in", values, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenNotIn(List<String> values) {
            addCriterion("accounttoken not in", values, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenBetween(String value1, String value2) {
            addCriterion("accounttoken between", value1, value2, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccounttokenNotBetween(String value1, String value2) {
            addCriterion("accounttoken not between", value1, value2, "accounttoken");
            return (Criteria) this;
        }

        public Criteria andAccountnumberIsNull() {
            addCriterion("accountnumber is null");
            return (Criteria) this;
        }

        public Criteria andAccountnumberIsNotNull() {
            addCriterion("accountnumber is not null");
            return (Criteria) this;
        }

        public Criteria andAccountnumberEqualTo(String value) {
            addCriterion("accountnumber =", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberNotEqualTo(String value) {
            addCriterion("accountnumber <>", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberGreaterThan(String value) {
            addCriterion("accountnumber >", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberGreaterThanOrEqualTo(String value) {
            addCriterion("accountnumber >=", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberLessThan(String value) {
            addCriterion("accountnumber <", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberLessThanOrEqualTo(String value) {
            addCriterion("accountnumber <=", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberLike(String value) {
            addCriterion("accountnumber like", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberNotLike(String value) {
            addCriterion("accountnumber not like", value, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberIn(List<String> values) {
            addCriterion("accountnumber in", values, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberNotIn(List<String> values) {
            addCriterion("accountnumber not in", values, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberBetween(String value1, String value2) {
            addCriterion("accountnumber between", value1, value2, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccountnumberNotBetween(String value1, String value2) {
            addCriterion("accountnumber not between", value1, value2, "accountnumber");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIsNull() {
            addCriterion("accounttype is null");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIsNotNull() {
            addCriterion("accounttype is not null");
            return (Criteria) this;
        }

        public Criteria andAccounttypeEqualTo(String value) {
            addCriterion("accounttype =", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotEqualTo(String value) {
            addCriterion("accounttype <>", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeGreaterThan(String value) {
            addCriterion("accounttype >", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeGreaterThanOrEqualTo(String value) {
            addCriterion("accounttype >=", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeLessThan(String value) {
            addCriterion("accounttype <", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeLessThanOrEqualTo(String value) {
            addCriterion("accounttype <=", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeLike(String value) {
            addCriterion("accounttype like", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotLike(String value) {
            addCriterion("accounttype not like", value, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeIn(List<String> values) {
            addCriterion("accounttype in", values, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotIn(List<String> values) {
            addCriterion("accounttype not in", values, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeBetween(String value1, String value2) {
            addCriterion("accounttype between", value1, value2, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccounttypeNotBetween(String value1, String value2) {
            addCriterion("accounttype not between", value1, value2, "accounttype");
            return (Criteria) this;
        }

        public Criteria andAccountemailIsNull() {
            addCriterion("accountemail is null");
            return (Criteria) this;
        }

        public Criteria andAccountemailIsNotNull() {
            addCriterion("accountemail is not null");
            return (Criteria) this;
        }

        public Criteria andAccountemailEqualTo(String value) {
            addCriterion("accountemail =", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailNotEqualTo(String value) {
            addCriterion("accountemail <>", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailGreaterThan(String value) {
            addCriterion("accountemail >", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailGreaterThanOrEqualTo(String value) {
            addCriterion("accountemail >=", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailLessThan(String value) {
            addCriterion("accountemail <", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailLessThanOrEqualTo(String value) {
            addCriterion("accountemail <=", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailLike(String value) {
            addCriterion("accountemail like", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailNotLike(String value) {
            addCriterion("accountemail not like", value, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailIn(List<String> values) {
            addCriterion("accountemail in", values, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailNotIn(List<String> values) {
            addCriterion("accountemail not in", values, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailBetween(String value1, String value2) {
            addCriterion("accountemail between", value1, value2, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountemailNotBetween(String value1, String value2) {
            addCriterion("accountemail not between", value1, value2, "accountemail");
            return (Criteria) this;
        }

        public Criteria andAccountdescIsNull() {
            addCriterion("accountdesc is null");
            return (Criteria) this;
        }

        public Criteria andAccountdescIsNotNull() {
            addCriterion("accountdesc is not null");
            return (Criteria) this;
        }

        public Criteria andAccountdescEqualTo(String value) {
            addCriterion("accountdesc =", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescNotEqualTo(String value) {
            addCriterion("accountdesc <>", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescGreaterThan(String value) {
            addCriterion("accountdesc >", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescGreaterThanOrEqualTo(String value) {
            addCriterion("accountdesc >=", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescLessThan(String value) {
            addCriterion("accountdesc <", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescLessThanOrEqualTo(String value) {
            addCriterion("accountdesc <=", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescLike(String value) {
            addCriterion("accountdesc like", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescNotLike(String value) {
            addCriterion("accountdesc not like", value, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescIn(List<String> values) {
            addCriterion("accountdesc in", values, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescNotIn(List<String> values) {
            addCriterion("accountdesc not in", values, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescBetween(String value1, String value2) {
            addCriterion("accountdesc between", value1, value2, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountdescNotBetween(String value1, String value2) {
            addCriterion("accountdesc not between", value1, value2, "accountdesc");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenIsNull() {
            addCriterion("accountaccesstoken is null");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenIsNotNull() {
            addCriterion("accountaccesstoken is not null");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenEqualTo(String value) {
            addCriterion("accountaccesstoken =", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenNotEqualTo(String value) {
            addCriterion("accountaccesstoken <>", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenGreaterThan(String value) {
            addCriterion("accountaccesstoken >", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenGreaterThanOrEqualTo(String value) {
            addCriterion("accountaccesstoken >=", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenLessThan(String value) {
            addCriterion("accountaccesstoken <", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenLessThanOrEqualTo(String value) {
            addCriterion("accountaccesstoken <=", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenLike(String value) {
            addCriterion("accountaccesstoken like", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenNotLike(String value) {
            addCriterion("accountaccesstoken not like", value, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenIn(List<String> values) {
            addCriterion("accountaccesstoken in", values, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenNotIn(List<String> values) {
            addCriterion("accountaccesstoken not in", values, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenBetween(String value1, String value2) {
            addCriterion("accountaccesstoken between", value1, value2, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountaccesstokenNotBetween(String value1, String value2) {
            addCriterion("accountaccesstoken not between", value1, value2, "accountaccesstoken");
            return (Criteria) this;
        }

        public Criteria andAccountappidIsNull() {
            addCriterion("accountappid is null");
            return (Criteria) this;
        }

        public Criteria andAccountappidIsNotNull() {
            addCriterion("accountappid is not null");
            return (Criteria) this;
        }

        public Criteria andAccountappidEqualTo(String value) {
            addCriterion("accountappid =", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidNotEqualTo(String value) {
            addCriterion("accountappid <>", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidGreaterThan(String value) {
            addCriterion("accountappid >", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidGreaterThanOrEqualTo(String value) {
            addCriterion("accountappid >=", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidLessThan(String value) {
            addCriterion("accountappid <", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidLessThanOrEqualTo(String value) {
            addCriterion("accountappid <=", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidLike(String value) {
            addCriterion("accountappid like", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidNotLike(String value) {
            addCriterion("accountappid not like", value, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidIn(List<String> values) {
            addCriterion("accountappid in", values, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidNotIn(List<String> values) {
            addCriterion("accountappid not in", values, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidBetween(String value1, String value2) {
            addCriterion("accountappid between", value1, value2, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappidNotBetween(String value1, String value2) {
            addCriterion("accountappid not between", value1, value2, "accountappid");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretIsNull() {
            addCriterion("accountappsecret is null");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretIsNotNull() {
            addCriterion("accountappsecret is not null");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretEqualTo(String value) {
            addCriterion("accountappsecret =", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretNotEqualTo(String value) {
            addCriterion("accountappsecret <>", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretGreaterThan(String value) {
            addCriterion("accountappsecret >", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretGreaterThanOrEqualTo(String value) {
            addCriterion("accountappsecret >=", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretLessThan(String value) {
            addCriterion("accountappsecret <", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretLessThanOrEqualTo(String value) {
            addCriterion("accountappsecret <=", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretLike(String value) {
            addCriterion("accountappsecret like", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretNotLike(String value) {
            addCriterion("accountappsecret not like", value, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretIn(List<String> values) {
            addCriterion("accountappsecret in", values, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretNotIn(List<String> values) {
            addCriterion("accountappsecret not in", values, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretBetween(String value1, String value2) {
            addCriterion("accountappsecret between", value1, value2, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAccountappsecretNotBetween(String value1, String value2) {
            addCriterion("accountappsecret not between", value1, value2, "accountappsecret");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeIsNull() {
            addCriterion("ADDTOEKNTIME is null");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeIsNotNull() {
            addCriterion("ADDTOEKNTIME is not null");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeEqualTo(Date value) {
            addCriterion("ADDTOEKNTIME =", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeNotEqualTo(Date value) {
            addCriterion("ADDTOEKNTIME <>", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeGreaterThan(Date value) {
            addCriterion("ADDTOEKNTIME >", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ADDTOEKNTIME >=", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeLessThan(Date value) {
            addCriterion("ADDTOEKNTIME <", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeLessThanOrEqualTo(Date value) {
            addCriterion("ADDTOEKNTIME <=", value, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeIn(List<Date> values) {
            addCriterion("ADDTOEKNTIME in", values, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeNotIn(List<Date> values) {
            addCriterion("ADDTOEKNTIME not in", values, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeBetween(Date value1, Date value2) {
            addCriterion("ADDTOEKNTIME between", value1, value2, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andAddtoekntimeNotBetween(Date value1, Date value2) {
            addCriterion("ADDTOEKNTIME not between", value1, value2, "addtoekntime");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidIsNull() {
            addCriterion("WEIXIN_ACCOUNTID is null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidIsNotNull() {
            addCriterion("WEIXIN_ACCOUNTID is not null");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNTID =", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidNotEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNTID <>", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidGreaterThan(String value) {
            addCriterion("WEIXIN_ACCOUNTID >", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidGreaterThanOrEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNTID >=", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidLessThan(String value) {
            addCriterion("WEIXIN_ACCOUNTID <", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidLessThanOrEqualTo(String value) {
            addCriterion("WEIXIN_ACCOUNTID <=", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidLike(String value) {
            addCriterion("WEIXIN_ACCOUNTID like", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidNotLike(String value) {
            addCriterion("WEIXIN_ACCOUNTID not like", value, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidIn(List<String> values) {
            addCriterion("WEIXIN_ACCOUNTID in", values, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidNotIn(List<String> values) {
            addCriterion("WEIXIN_ACCOUNTID not in", values, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidBetween(String value1, String value2) {
            addCriterion("WEIXIN_ACCOUNTID between", value1, value2, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andWeixinAccountidNotBetween(String value1, String value2) {
            addCriterion("WEIXIN_ACCOUNTID not between", value1, value2, "weixinAccountid");
            return (Criteria) this;
        }

        public Criteria andApiticketIsNull() {
            addCriterion("apiticket is null");
            return (Criteria) this;
        }

        public Criteria andApiticketIsNotNull() {
            addCriterion("apiticket is not null");
            return (Criteria) this;
        }

        public Criteria andApiticketEqualTo(String value) {
            addCriterion("apiticket =", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketNotEqualTo(String value) {
            addCriterion("apiticket <>", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketGreaterThan(String value) {
            addCriterion("apiticket >", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketGreaterThanOrEqualTo(String value) {
            addCriterion("apiticket >=", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketLessThan(String value) {
            addCriterion("apiticket <", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketLessThanOrEqualTo(String value) {
            addCriterion("apiticket <=", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketLike(String value) {
            addCriterion("apiticket like", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketNotLike(String value) {
            addCriterion("apiticket not like", value, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketIn(List<String> values) {
            addCriterion("apiticket in", values, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketNotIn(List<String> values) {
            addCriterion("apiticket not in", values, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketBetween(String value1, String value2) {
            addCriterion("apiticket between", value1, value2, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketNotBetween(String value1, String value2) {
            addCriterion("apiticket not between", value1, value2, "apiticket");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeIsNull() {
            addCriterion("apiticketttime is null");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeIsNotNull() {
            addCriterion("apiticketttime is not null");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeEqualTo(Date value) {
            addCriterion("apiticketttime =", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeNotEqualTo(Date value) {
            addCriterion("apiticketttime <>", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeGreaterThan(Date value) {
            addCriterion("apiticketttime >", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("apiticketttime >=", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeLessThan(Date value) {
            addCriterion("apiticketttime <", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeLessThanOrEqualTo(Date value) {
            addCriterion("apiticketttime <=", value, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeIn(List<Date> values) {
            addCriterion("apiticketttime in", values, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeNotIn(List<Date> values) {
            addCriterion("apiticketttime not in", values, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeBetween(Date value1, Date value2) {
            addCriterion("apiticketttime between", value1, value2, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andApiticketttimeNotBetween(Date value1, Date value2) {
            addCriterion("apiticketttime not between", value1, value2, "apiticketttime");
            return (Criteria) this;
        }

        public Criteria andJsapiticketIsNull() {
            addCriterion("jsapiticket is null");
            return (Criteria) this;
        }

        public Criteria andJsapiticketIsNotNull() {
            addCriterion("jsapiticket is not null");
            return (Criteria) this;
        }

        public Criteria andJsapiticketEqualTo(String value) {
            addCriterion("jsapiticket =", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketNotEqualTo(String value) {
            addCriterion("jsapiticket <>", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketGreaterThan(String value) {
            addCriterion("jsapiticket >", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketGreaterThanOrEqualTo(String value) {
            addCriterion("jsapiticket >=", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketLessThan(String value) {
            addCriterion("jsapiticket <", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketLessThanOrEqualTo(String value) {
            addCriterion("jsapiticket <=", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketLike(String value) {
            addCriterion("jsapiticket like", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketNotLike(String value) {
            addCriterion("jsapiticket not like", value, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketIn(List<String> values) {
            addCriterion("jsapiticket in", values, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketNotIn(List<String> values) {
            addCriterion("jsapiticket not in", values, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketBetween(String value1, String value2) {
            addCriterion("jsapiticket between", value1, value2, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapiticketNotBetween(String value1, String value2) {
            addCriterion("jsapiticket not between", value1, value2, "jsapiticket");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeIsNull() {
            addCriterion("jsapitickettime is null");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeIsNotNull() {
            addCriterion("jsapitickettime is not null");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeEqualTo(Date value) {
            addCriterion("jsapitickettime =", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeNotEqualTo(Date value) {
            addCriterion("jsapitickettime <>", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeGreaterThan(Date value) {
            addCriterion("jsapitickettime >", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeGreaterThanOrEqualTo(Date value) {
            addCriterion("jsapitickettime >=", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeLessThan(Date value) {
            addCriterion("jsapitickettime <", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeLessThanOrEqualTo(Date value) {
            addCriterion("jsapitickettime <=", value, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeIn(List<Date> values) {
            addCriterion("jsapitickettime in", values, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeNotIn(List<Date> values) {
            addCriterion("jsapitickettime not in", values, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeBetween(Date value1, Date value2) {
            addCriterion("jsapitickettime between", value1, value2, "jsapitickettime");
            return (Criteria) this;
        }

        public Criteria andJsapitickettimeNotBetween(Date value1, Date value2) {
            addCriterion("jsapitickettime not between", value1, value2, "jsapitickettime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_account
     *
     * @mbg.generated do_not_delete_during_merge Sat Mar 04 11:19:51 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}