package com.hq.tony.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class WeixinAccesstoken implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_accesstoken.ID
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_accesstoken.access_token
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_accesstoken.addtime
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_accesstoken.expires_in
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private Integer expiresIn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_accesstoken.ID
     *
     * @return the value of weixin_accesstoken.ID
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_accesstoken.ID
     *
     * @param id the value for weixin_accesstoken.ID
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_accesstoken.access_token
     *
     * @return the value of weixin_accesstoken.access_token
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_accesstoken.access_token
     *
     * @param accessToken the value for weixin_accesstoken.access_token
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_accesstoken.addtime
     *
     * @return the value of weixin_accesstoken.addtime
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_accesstoken.addtime
     *
     * @param addtime the value for weixin_accesstoken.addtime
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_accesstoken.expires_in
     *
     * @return the value of weixin_accesstoken.expires_in
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public Integer getExpiresIn() {
        return expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_accesstoken.expires_in
     *
     * @param expiresIn the value for weixin_accesstoken.expires_in
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    public void setExpiresIn(Integer expiresIn) {
        this.expiresIn = expiresIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accessToken=").append(accessToken);
        sb.append(", addtime=").append(addtime);
        sb.append(", expiresIn=").append(expiresIn);
        sb.append("]");
        return sb.toString();
    }
}