package com.hq.tony.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class WeixinCmsSite implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.COMPANY_TEL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String companyTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String createName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.SITE_LOGO
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String siteLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.SITE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String siteName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.SITE_TEMPLATE_STYLE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String siteTemplateStyle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_cms_site.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.ID
     *
     * @return the value of weixin_cms_site.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.ID
     *
     * @param id the value for weixin_cms_site.ID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.ACCOUNTID
     *
     * @return the value of weixin_cms_site.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.ACCOUNTID
     *
     * @param accountid the value for weixin_cms_site.ACCOUNTID
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setAccountid(String accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.COMPANY_TEL
     *
     * @return the value of weixin_cms_site.COMPANY_TEL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.COMPANY_TEL
     *
     * @param companyTel the value for weixin_cms_site.COMPANY_TEL
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.CREATE_DATE
     *
     * @return the value of weixin_cms_site.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.CREATE_DATE
     *
     * @param createDate the value for weixin_cms_site.CREATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.CREATE_NAME
     *
     * @return the value of weixin_cms_site.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.CREATE_NAME
     *
     * @param createName the value for weixin_cms_site.CREATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setCreateName(String createName) {
        this.createName = createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.SITE_LOGO
     *
     * @return the value of weixin_cms_site.SITE_LOGO
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getSiteLogo() {
        return siteLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.SITE_LOGO
     *
     * @param siteLogo the value for weixin_cms_site.SITE_LOGO
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setSiteLogo(String siteLogo) {
        this.siteLogo = siteLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.SITE_NAME
     *
     * @return the value of weixin_cms_site.SITE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.SITE_NAME
     *
     * @param siteName the value for weixin_cms_site.SITE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.SITE_TEMPLATE_STYLE
     *
     * @return the value of weixin_cms_site.SITE_TEMPLATE_STYLE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getSiteTemplateStyle() {
        return siteTemplateStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.SITE_TEMPLATE_STYLE
     *
     * @param siteTemplateStyle the value for weixin_cms_site.SITE_TEMPLATE_STYLE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setSiteTemplateStyle(String siteTemplateStyle) {
        this.siteTemplateStyle = siteTemplateStyle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.UPDATE_DATE
     *
     * @return the value of weixin_cms_site.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.UPDATE_DATE
     *
     * @param updateDate the value for weixin_cms_site.UPDATE_DATE
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_cms_site.UPDATE_NAME
     *
     * @return the value of weixin_cms_site.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_cms_site.UPDATE_NAME
     *
     * @param updateName the value for weixin_cms_site.UPDATE_NAME
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountid=").append(accountid);
        sb.append(", companyTel=").append(companyTel);
        sb.append(", createDate=").append(createDate);
        sb.append(", createName=").append(createName);
        sb.append(", siteLogo=").append(siteLogo);
        sb.append(", siteName=").append(siteName);
        sb.append(", siteTemplateStyle=").append(siteTemplateStyle);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", updateName=").append(updateName);
        sb.append("]");
        return sb.toString();
    }
}