package com.hq.peaches.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class Member implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.id
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.name
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.sex
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.phone
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.card_no
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String card_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String mmsg_openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.ali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String ali_openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pmmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String pmmsg_openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.pali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String pali_openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.black
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String black;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private Date update_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.create_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String create_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.update_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String update_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.bind
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String bind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.mchId
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private String mchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.visit_num
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private Integer visit_num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.id
     *
     * @return the value of member.id
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.id
     *
     * @param id the value for member.id
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.name
     *
     * @return the value of member.name
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.name
     *
     * @param name the value for member.name
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.sex
     *
     * @return the value of member.sex
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.sex
     *
     * @param sex the value for member.sex
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.phone
     *
     * @return the value of member.phone
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.phone
     *
     * @param phone the value for member.phone
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.card_no
     *
     * @return the value of member.card_no
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getCard_no() {
        return card_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.card_no
     *
     * @param card_no the value for member.card_no
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setCard_no(String card_no) {
        this.card_no = card_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mmsg_openid
     *
     * @return the value of member.mmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getMmsg_openid() {
        return mmsg_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mmsg_openid
     *
     * @param mmsg_openid the value for member.mmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setMmsg_openid(String mmsg_openid) {
        this.mmsg_openid = mmsg_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.ali_openid
     *
     * @return the value of member.ali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getAli_openid() {
        return ali_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.ali_openid
     *
     * @param ali_openid the value for member.ali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setAli_openid(String ali_openid) {
        this.ali_openid = ali_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pmmsg_openid
     *
     * @return the value of member.pmmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getPmmsg_openid() {
        return pmmsg_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pmmsg_openid
     *
     * @param pmmsg_openid the value for member.pmmsg_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setPmmsg_openid(String pmmsg_openid) {
        this.pmmsg_openid = pmmsg_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.pali_openid
     *
     * @return the value of member.pali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getPali_openid() {
        return pali_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.pali_openid
     *
     * @param pali_openid the value for member.pali_openid
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setPali_openid(String pali_openid) {
        this.pali_openid = pali_openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.black
     *
     * @return the value of member.black
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getBlack() {
        return black;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.black
     *
     * @param black the value for member.black
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setBlack(String black) {
        this.black = black;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_time
     *
     * @return the value of member.create_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_time
     *
     * @param create_time the value for member.create_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_time
     *
     * @return the value of member.update_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_time
     *
     * @param update_time the value for member.update_time
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.create_user
     *
     * @return the value of member.create_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getCreate_user() {
        return create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.create_user
     *
     * @param create_user the value for member.create_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setCreate_user(String create_user) {
        this.create_user = create_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.update_user
     *
     * @return the value of member.update_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getUpdate_user() {
        return update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.update_user
     *
     * @param update_user the value for member.update_user
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setUpdate_user(String update_user) {
        this.update_user = update_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.bind
     *
     * @return the value of member.bind
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getBind() {
        return bind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.bind
     *
     * @param bind the value for member.bind
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setBind(String bind) {
        this.bind = bind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.mchId
     *
     * @return the value of member.mchId
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.mchId
     *
     * @param mchId the value for member.mchId
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setMchId(String mchId) {
        this.mchId = mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.visit_num
     *
     * @return the value of member.visit_num
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public Integer getVisit_num() {
        return visit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.visit_num
     *
     * @param visit_num the value for member.visit_num
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    public void setVisit_num(Integer visit_num) {
        this.visit_num = visit_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbg.generated Fri Jan 20 21:18:24 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", phone=").append(phone);
        sb.append(", card_no=").append(card_no);
        sb.append(", mmsg_openid=").append(mmsg_openid);
        sb.append(", ali_openid=").append(ali_openid);
        sb.append(", pmmsg_openid=").append(pmmsg_openid);
        sb.append(", pali_openid=").append(pali_openid);
        sb.append(", black=").append(black);
        sb.append(", status=").append(status);
        sb.append(", create_time=").append(create_time);
        sb.append(", update_time=").append(update_time);
        sb.append(", create_user=").append(create_user);
        sb.append(", update_user=").append(update_user);
        sb.append(", bind=").append(bind);
        sb.append(", mchId=").append(mchId);
        sb.append(", visit_num=").append(visit_num);
        sb.append("]");
        return sb.toString();
    }
}