package com.hq.elva.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class TBasBkcd implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bas_bkcd.LBNK_CD
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private String lbnkCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bas_bkcd.BNK_NM
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private String bnkNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bas_bkcd.CORP_ORG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private String corpOrg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bas_bkcd.FLG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private String flg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_bas_bkcd.TM_SMP
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private Date tmSmp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bas_bkcd.LBNK_CD
     *
     * @return the value of t_bas_bkcd.LBNK_CD
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public String getLbnkCd() {
        return lbnkCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bas_bkcd.LBNK_CD
     *
     * @param lbnkCd the value for t_bas_bkcd.LBNK_CD
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setLbnkCd(String lbnkCd) {
        this.lbnkCd = lbnkCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bas_bkcd.BNK_NM
     *
     * @return the value of t_bas_bkcd.BNK_NM
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public String getBnkNm() {
        return bnkNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bas_bkcd.BNK_NM
     *
     * @param bnkNm the value for t_bas_bkcd.BNK_NM
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setBnkNm(String bnkNm) {
        this.bnkNm = bnkNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bas_bkcd.CORP_ORG
     *
     * @return the value of t_bas_bkcd.CORP_ORG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public String getCorpOrg() {
        return corpOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bas_bkcd.CORP_ORG
     *
     * @param corpOrg the value for t_bas_bkcd.CORP_ORG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setCorpOrg(String corpOrg) {
        this.corpOrg = corpOrg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bas_bkcd.FLG
     *
     * @return the value of t_bas_bkcd.FLG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public String getFlg() {
        return flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bas_bkcd.FLG
     *
     * @param flg the value for t_bas_bkcd.FLG
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setFlg(String flg) {
        this.flg = flg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_bas_bkcd.TM_SMP
     *
     * @return the value of t_bas_bkcd.TM_SMP
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public Date getTmSmp() {
        return tmSmp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_bas_bkcd.TM_SMP
     *
     * @param tmSmp the value for t_bas_bkcd.TM_SMP
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setTmSmp(Date tmSmp) {
        this.tmSmp = tmSmp;
    }
}