package com.hq.elva.entity.generate;

import java.io.Serializable;
import java.util.Date;

public class TBasConfig implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.config_id
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private Long configId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.config_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String configName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.config_value
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String configValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.config_exp
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String configExp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.service_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String serviceName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.service_ip
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String serviceIp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.dynamic
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String dynamic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.oper_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private Date operTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.oper_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String operUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.update_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_bas_config.update_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private String updateUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.config_id
	 * @return  the value of t_bas_config.config_id
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public Long getConfigId() {
		return configId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.config_id
	 * @param configId  the value for t_bas_config.config_id
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setConfigId(Long configId) {
		this.configId = configId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.config_name
	 * @return  the value of t_bas_config.config_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getConfigName() {
		return configName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.config_name
	 * @param configName  the value for t_bas_config.config_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setConfigName(String configName) {
		this.configName = configName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.config_value
	 * @return  the value of t_bas_config.config_value
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getConfigValue() {
		return configValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.config_value
	 * @param configValue  the value for t_bas_config.config_value
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.config_exp
	 * @return  the value of t_bas_config.config_exp
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getConfigExp() {
		return configExp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.config_exp
	 * @param configExp  the value for t_bas_config.config_exp
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setConfigExp(String configExp) {
		this.configExp = configExp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.service_name
	 * @return  the value of t_bas_config.service_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getServiceName() {
		return serviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.service_name
	 * @param serviceName  the value for t_bas_config.service_name
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.service_ip
	 * @return  the value of t_bas_config.service_ip
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getServiceIp() {
		return serviceIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.service_ip
	 * @param serviceIp  the value for t_bas_config.service_ip
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setServiceIp(String serviceIp) {
		this.serviceIp = serviceIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.dynamic
	 * @return  the value of t_bas_config.dynamic
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getDynamic() {
		return dynamic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.dynamic
	 * @param dynamic  the value for t_bas_config.dynamic
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setDynamic(String dynamic) {
		this.dynamic = dynamic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.oper_time
	 * @return  the value of t_bas_config.oper_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public Date getOperTime() {
		return operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.oper_time
	 * @param operTime  the value for t_bas_config.oper_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.oper_user
	 * @return  the value of t_bas_config.oper_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getOperUser() {
		return operUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.oper_user
	 * @param operUser  the value for t_bas_config.oper_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setOperUser(String operUser) {
		this.operUser = operUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.update_time
	 * @return  the value of t_bas_config.update_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.update_time
	 * @param updateTime  the value for t_bas_config.update_time
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_bas_config.update_user
	 * @return  the value of t_bas_config.update_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public String getUpdateUser() {
		return updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_bas_config.update_user
	 * @param updateUser  the value for t_bas_config.update_user
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_bas_config
	 * @mbggenerated  Mon Nov 07 14:10:41 CST 2016
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", configId=").append(configId);
		sb.append(", configName=").append(configName);
		sb.append(", configValue=").append(configValue);
		sb.append(", configExp=").append(configExp);
		sb.append(", serviceName=").append(serviceName);
		sb.append(", serviceIp=").append(serviceIp);
		sb.append(", dynamic=").append(dynamic);
		sb.append(", operTime=").append(operTime);
		sb.append(", operUser=").append(operUser);
		sb.append(", updateTime=").append(updateTime);
		sb.append(", updateUser=").append(updateUser);
		sb.append("]");
		return sb.toString();
	}
}