package com.hq.elva.entity.generate;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TBasBkcdExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public TBasBkcdExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLbnkCdIsNull() {
            addCriterion("LBNK_CD is null");
            return (Criteria) this;
        }

        public Criteria andLbnkCdIsNotNull() {
            addCriterion("LBNK_CD is not null");
            return (Criteria) this;
        }

        public Criteria andLbnkCdEqualTo(String value) {
            addCriterion("LBNK_CD =", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdNotEqualTo(String value) {
            addCriterion("LBNK_CD <>", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdGreaterThan(String value) {
            addCriterion("LBNK_CD >", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdGreaterThanOrEqualTo(String value) {
            addCriterion("LBNK_CD >=", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdLessThan(String value) {
            addCriterion("LBNK_CD <", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdLessThanOrEqualTo(String value) {
            addCriterion("LBNK_CD <=", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdLike(String value) {
            addCriterion("LBNK_CD like", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdNotLike(String value) {
            addCriterion("LBNK_CD not like", value, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdIn(List<String> values) {
            addCriterion("LBNK_CD in", values, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdNotIn(List<String> values) {
            addCriterion("LBNK_CD not in", values, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdBetween(String value1, String value2) {
            addCriterion("LBNK_CD between", value1, value2, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andLbnkCdNotBetween(String value1, String value2) {
            addCriterion("LBNK_CD not between", value1, value2, "lbnkCd");
            return (Criteria) this;
        }

        public Criteria andBnkNmIsNull() {
            addCriterion("BNK_NM is null");
            return (Criteria) this;
        }

        public Criteria andBnkNmIsNotNull() {
            addCriterion("BNK_NM is not null");
            return (Criteria) this;
        }

        public Criteria andBnkNmEqualTo(String value) {
            addCriterion("BNK_NM =", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmNotEqualTo(String value) {
            addCriterion("BNK_NM <>", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmGreaterThan(String value) {
            addCriterion("BNK_NM >", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmGreaterThanOrEqualTo(String value) {
            addCriterion("BNK_NM >=", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmLessThan(String value) {
            addCriterion("BNK_NM <", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmLessThanOrEqualTo(String value) {
            addCriterion("BNK_NM <=", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmLike(String value) {
            addCriterion("BNK_NM like", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmNotLike(String value) {
            addCriterion("BNK_NM not like", value, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmIn(List<String> values) {
            addCriterion("BNK_NM in", values, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmNotIn(List<String> values) {
            addCriterion("BNK_NM not in", values, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmBetween(String value1, String value2) {
            addCriterion("BNK_NM between", value1, value2, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andBnkNmNotBetween(String value1, String value2) {
            addCriterion("BNK_NM not between", value1, value2, "bnkNm");
            return (Criteria) this;
        }

        public Criteria andCorpOrgIsNull() {
            addCriterion("CORP_ORG is null");
            return (Criteria) this;
        }

        public Criteria andCorpOrgIsNotNull() {
            addCriterion("CORP_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andCorpOrgEqualTo(String value) {
            addCriterion("CORP_ORG =", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgNotEqualTo(String value) {
            addCriterion("CORP_ORG <>", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgGreaterThan(String value) {
            addCriterion("CORP_ORG >", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgGreaterThanOrEqualTo(String value) {
            addCriterion("CORP_ORG >=", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgLessThan(String value) {
            addCriterion("CORP_ORG <", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgLessThanOrEqualTo(String value) {
            addCriterion("CORP_ORG <=", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgLike(String value) {
            addCriterion("CORP_ORG like", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgNotLike(String value) {
            addCriterion("CORP_ORG not like", value, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgIn(List<String> values) {
            addCriterion("CORP_ORG in", values, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgNotIn(List<String> values) {
            addCriterion("CORP_ORG not in", values, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgBetween(String value1, String value2) {
            addCriterion("CORP_ORG between", value1, value2, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andCorpOrgNotBetween(String value1, String value2) {
            addCriterion("CORP_ORG not between", value1, value2, "corpOrg");
            return (Criteria) this;
        }

        public Criteria andFlgIsNull() {
            addCriterion("FLG is null");
            return (Criteria) this;
        }

        public Criteria andFlgIsNotNull() {
            addCriterion("FLG is not null");
            return (Criteria) this;
        }

        public Criteria andFlgEqualTo(String value) {
            addCriterion("FLG =", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgNotEqualTo(String value) {
            addCriterion("FLG <>", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgGreaterThan(String value) {
            addCriterion("FLG >", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgGreaterThanOrEqualTo(String value) {
            addCriterion("FLG >=", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgLessThan(String value) {
            addCriterion("FLG <", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgLessThanOrEqualTo(String value) {
            addCriterion("FLG <=", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgLike(String value) {
            addCriterion("FLG like", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgNotLike(String value) {
            addCriterion("FLG not like", value, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgIn(List<String> values) {
            addCriterion("FLG in", values, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgNotIn(List<String> values) {
            addCriterion("FLG not in", values, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgBetween(String value1, String value2) {
            addCriterion("FLG between", value1, value2, "flg");
            return (Criteria) this;
        }

        public Criteria andFlgNotBetween(String value1, String value2) {
            addCriterion("FLG not between", value1, value2, "flg");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNull() {
            addCriterion("TM_SMP is null");
            return (Criteria) this;
        }

        public Criteria andTmSmpIsNotNull() {
            addCriterion("TM_SMP is not null");
            return (Criteria) this;
        }

        public Criteria andTmSmpEqualTo(Date value) {
            addCriterion("TM_SMP =", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotEqualTo(Date value) {
            addCriterion("TM_SMP <>", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThan(Date value) {
            addCriterion("TM_SMP >", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpGreaterThanOrEqualTo(Date value) {
            addCriterion("TM_SMP >=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThan(Date value) {
            addCriterion("TM_SMP <", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpLessThanOrEqualTo(Date value) {
            addCriterion("TM_SMP <=", value, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpIn(List<Date> values) {
            addCriterion("TM_SMP in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotIn(List<Date> values) {
            addCriterion("TM_SMP not in", values, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpBetween(Date value1, Date value2) {
            addCriterion("TM_SMP between", value1, value2, "tmSmp");
            return (Criteria) this;
        }

        public Criteria andTmSmpNotBetween(Date value1, Date value2) {
            addCriterion("TM_SMP not between", value1, value2, "tmSmp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated do_not_delete_during_merge Thu Nov 03 17:28:37 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_bas_bkcd
     *
     * @mbggenerated Thu Nov 03 17:28:37 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}