package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinHdrecord;
import com.hq.tony.entity.generate.WeixinHdrecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinHdrecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinHdrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinHdrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinHdrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinHdrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHdrecord> selectByExampleWithRowbounds(WeixinHdrecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHdrecord> selectByExample(WeixinHdrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinHdrecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinHdrecord record, @Param("example") WeixinHdrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinHdrecord record, @Param("example") WeixinHdrecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinHdrecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_hdrecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinHdrecord record);
}