package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinExpandconfig;
import com.hq.tony.entity.generate.WeixinExpandconfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinExpandconfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinExpandconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinExpandconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinExpandconfig> selectByExampleWithBLOBsWithRowbounds(WeixinExpandconfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinExpandconfig> selectByExampleWithBLOBs(WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinExpandconfig> selectByExampleWithRowbounds(WeixinExpandconfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinExpandconfig> selectByExample(WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinExpandconfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinExpandconfig record, @Param("example") WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinExpandconfig record, @Param("example") WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinExpandconfig record, @Param("example") WeixinExpandconfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinExpandconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinExpandconfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_expandconfig
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinExpandconfig record);
}