package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinSubscribe;
import com.hq.tony.entity.generate.WeixinSubscribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinSubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinSubscribe> selectByExampleWithRowbounds(WeixinSubscribeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinSubscribe> selectByExample(WeixinSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinSubscribe selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinSubscribe record, @Param("example") WeixinSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinSubscribe record, @Param("example") WeixinSubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinSubscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_subscribe
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinSubscribe record);
}