package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinAutoresponse;
import com.hq.tony.entity.generate.WeixinAutoresponseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinAutoresponseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinAutoresponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinAutoresponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinAutoresponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinAutoresponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinAutoresponse> selectByExampleWithRowbounds(WeixinAutoresponseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinAutoresponse> selectByExample(WeixinAutoresponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinAutoresponse selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinAutoresponse record, @Param("example") WeixinAutoresponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinAutoresponse record, @Param("example") WeixinAutoresponseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinAutoresponse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_autoresponse
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinAutoresponse record);
}