package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinPrizerecord;
import com.hq.tony.entity.generate.WeixinPrizerecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinPrizerecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinPrizerecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinPrizerecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinPrizerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinPrizerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinPrizerecord> selectByExampleWithRowbounds(WeixinPrizerecordExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinPrizerecord> selectByExample(WeixinPrizerecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinPrizerecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinPrizerecord record, @Param("example") WeixinPrizerecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinPrizerecord record, @Param("example") WeixinPrizerecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinPrizerecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_prizerecord
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinPrizerecord record);
}