package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinNewstemplate;
import com.hq.tony.entity.generate.WeixinNewstemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinNewstemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinNewstemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinNewstemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinNewstemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinNewstemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinNewstemplate> selectByExampleWithRowbounds(WeixinNewstemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinNewstemplate> selectByExample(WeixinNewstemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinNewstemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinNewstemplate record, @Param("example") WeixinNewstemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinNewstemplate record, @Param("example") WeixinNewstemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinNewstemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_newstemplate
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinNewstemplate record);
}