package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinCmsStyle;
import com.hq.tony.entity.generate.WeixinCmsStyleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinCmsStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinCmsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinCmsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinCmsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinCmsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsStyle> selectByExampleWithRowbounds(WeixinCmsStyleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsStyle> selectByExample(WeixinCmsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinCmsStyle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinCmsStyle record, @Param("example") WeixinCmsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinCmsStyle record, @Param("example") WeixinCmsStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinCmsStyle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_style
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinCmsStyle record);
}