package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinOpenAccount;
import com.hq.tony.entity.generate.WeixinOpenAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinOpenAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinOpenAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinOpenAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinOpenAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinOpenAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinOpenAccount> selectByExampleWithRowbounds(WeixinOpenAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinOpenAccount> selectByExample(WeixinOpenAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinOpenAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinOpenAccount record, @Param("example") WeixinOpenAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinOpenAccount record, @Param("example") WeixinOpenAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinOpenAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_open_account
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinOpenAccount record);
}