package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinCmsAd;
import com.hq.tony.entity.generate.WeixinCmsAdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinCmsAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinCmsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinCmsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinCmsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinCmsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsAd> selectByExampleWithRowbounds(WeixinCmsAdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsAd> selectByExample(WeixinCmsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinCmsAd selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinCmsAd record, @Param("example") WeixinCmsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinCmsAd record, @Param("example") WeixinCmsAdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinCmsAd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_ad
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinCmsAd record);
}