package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinLinksucai;
import com.hq.tony.entity.generate.WeixinLinksucaiExample;
import com.hq.tony.entity.generate.WeixinLinksucaiWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinLinksucaiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinLinksucaiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinLinksucaiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinLinksucaiWithBLOBs> selectByExampleWithBLOBsWithRowbounds(WeixinLinksucaiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinLinksucaiWithBLOBs> selectByExampleWithBLOBs(WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinLinksucai> selectByExampleWithRowbounds(WeixinLinksucaiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinLinksucai> selectByExample(WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinLinksucaiWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinLinksucaiWithBLOBs record, @Param("example") WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinLinksucaiWithBLOBs record, @Param("example") WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinLinksucai record, @Param("example") WeixinLinksucaiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinLinksucaiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinLinksucaiWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_linksucai
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinLinksucai record);
}