package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinPhotoAlbum;
import com.hq.tony.entity.generate.WeixinPhotoAlbumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinPhotoAlbumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinPhotoAlbum> selectByExampleWithRowbounds(WeixinPhotoAlbumExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinPhotoAlbum> selectByExample(WeixinPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinPhotoAlbum selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinPhotoAlbum record, @Param("example") WeixinPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinPhotoAlbum record, @Param("example") WeixinPhotoAlbumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinPhotoAlbum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo_album
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinPhotoAlbum record);
}