package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinTexttemplate;
import com.hq.tony.entity.generate.WeixinTexttemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinTexttemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinTexttemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinTexttemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinTexttemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinTexttemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinTexttemplate> selectByExampleWithRowbounds(WeixinTexttemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinTexttemplate> selectByExample(WeixinTexttemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinTexttemplate selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinTexttemplate record, @Param("example") WeixinTexttemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinTexttemplate record, @Param("example") WeixinTexttemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinTexttemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_texttemplate
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinTexttemplate record);
}