package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinReceivetext;
import com.hq.tony.entity.generate.WeixinReceivetextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinReceivetextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinReceivetextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinReceivetextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinReceivetext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinReceivetext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinReceivetext> selectByExampleWithRowbounds(WeixinReceivetextExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinReceivetext> selectByExample(WeixinReceivetextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinReceivetext selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinReceivetext record, @Param("example") WeixinReceivetextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinReceivetext record, @Param("example") WeixinReceivetextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinReceivetext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_receivetext
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinReceivetext record);
}