package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinAccount;
import com.hq.tony.entity.generate.WeixinAccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinAccount> selectByExampleWithRowbounds(WeixinAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinAccount> selectByExample(WeixinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinAccount record, @Param("example") WeixinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinAccount record, @Param("example") WeixinAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_account
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinAccount record);
}