package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinHuodong;
import com.hq.tony.entity.generate.WeixinHuodongExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinHuodongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinHuodong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinHuodong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHuodong> selectByExampleWithBLOBsWithRowbounds(WeixinHuodongExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHuodong> selectByExampleWithBLOBs(WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHuodong> selectByExampleWithRowbounds(WeixinHuodongExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinHuodong> selectByExample(WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinHuodong selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinHuodong record, @Param("example") WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WeixinHuodong record, @Param("example") WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinHuodong record, @Param("example") WeixinHuodongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinHuodong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WeixinHuodong record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_huodong
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinHuodong record);
}