package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinCmsArticle;
import com.hq.tony.entity.generate.WeixinCmsArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinCmsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinCmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinCmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinCmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinCmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinCmsArticle> selectByExampleWithRowbounds(WeixinCmsArticleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinCmsArticle> selectByExample(WeixinCmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinCmsArticle selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinCmsArticle record, @Param("example") WeixinCmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinCmsArticle record, @Param("example") WeixinCmsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinCmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_article
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinCmsArticle record);
}