package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinAccesstoken;
import com.hq.tony.entity.generate.WeixinAccesstokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinAccesstokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinAccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinAccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinAccesstoken> selectByExampleWithRowbounds(WeixinAccesstokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    List<WeixinAccesstoken> selectByExample(WeixinAccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    WeixinAccesstoken selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinAccesstoken record, @Param("example") WeixinAccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByExample(@Param("record") WeixinAccesstoken record, @Param("example") WeixinAccesstokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinAccesstoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_accesstoken
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int updateByPrimaryKey(WeixinAccesstoken record);
}