package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinPhoto;
import com.hq.tony.entity.generate.WeixinPhotoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinPhoto> selectByExampleWithRowbounds(WeixinPhotoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinPhoto> selectByExample(WeixinPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinPhoto selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinPhoto record, @Param("example") WeixinPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinPhoto record, @Param("example") WeixinPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_photo
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinPhoto record);
}