package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinCmsMenu;
import com.hq.tony.entity.generate.WeixinCmsMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinCmsMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    long countByExample(WeixinCmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByExample(WeixinCmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insert(WeixinCmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:50 CST 2017
     */
    int insertSelective(WeixinCmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsMenu> selectByExampleWithRowbounds(WeixinCmsMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsMenu> selectByExample(WeixinCmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinCmsMenu selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinCmsMenu record, @Param("example") WeixinCmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinCmsMenu record, @Param("example") WeixinCmsMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinCmsMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_menu
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinCmsMenu record);
}