package com.hq.tony.dao.generate;

import com.hq.tony.entity.generate.WeixinCmsSite;
import com.hq.tony.entity.generate.WeixinCmsSiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WeixinCmsSiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    long countByExample(WeixinCmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByExample(WeixinCmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insert(WeixinCmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int insertSelective(WeixinCmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsSite> selectByExampleWithRowbounds(WeixinCmsSiteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    List<WeixinCmsSite> selectByExample(WeixinCmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    WeixinCmsSite selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") WeixinCmsSite record, @Param("example") WeixinCmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByExample(@Param("record") WeixinCmsSite record, @Param("example") WeixinCmsSiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKeySelective(WeixinCmsSite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weixin_cms_site
     *
     * @mbg.generated Sat Mar 04 11:19:51 CST 2017
     */
    int updateByPrimaryKey(WeixinCmsSite record);
}