package com.hq.ellie.entity.generate;

import java.io.Serializable;

public class CustomerKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.openid
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mchId
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    private String mchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.openid
     *
     * @return the value of customer.openid
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.openid
     *
     * @param openid the value for customer.openid
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    public void setOpenid(String openid) {
        this.openid = openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mchId
     *
     * @return the value of customer.mchId
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mchId
     *
     * @param mchId the value for customer.mchId
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    public void setMchId(String mchId) {
        this.mchId = mchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated Tue Feb 21 01:23:58 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", openid=").append(openid);
        sb.append(", mchId=").append(mchId);
        sb.append("]");
        return sb.toString();
    }
}