package com.hq.flood.dao.generate;

import com.hq.flood.entity.generate.TFloodPrd;
import com.hq.flood.entity.generate.TFloodPrdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFloodPrdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    long countByExample(TFloodPrdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByExample(TFloodPrdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByPrimaryKey(String prdCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insert(TFloodPrd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insertSelective(TFloodPrd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodPrd> selectByExampleWithRowbounds(TFloodPrdExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodPrd> selectByExample(TFloodPrdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    TFloodPrd selectByPrimaryKey(String prdCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFloodPrd record, @Param("example") TFloodPrdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExample(@Param("record") TFloodPrd record, @Param("example") TFloodPrdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKeySelective(TFloodPrd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_prd
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKey(TFloodPrd record);
}