package com.hq.flood.dao.generate;

import com.hq.flood.entity.generate.TFloodRoleResource;
import com.hq.flood.entity.generate.TFloodRoleResourceExample;
import com.hq.flood.entity.generate.TFloodRoleResourceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFloodRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    long countByExample(TFloodRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByExample(TFloodRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByPrimaryKey(TFloodRoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insert(TFloodRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insertSelective(TFloodRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodRoleResource> selectByExampleWithRowbounds(TFloodRoleResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodRoleResource> selectByExample(TFloodRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    TFloodRoleResource selectByPrimaryKey(TFloodRoleResourceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFloodRoleResource record, @Param("example") TFloodRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExample(@Param("record") TFloodRoleResource record, @Param("example") TFloodRoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKeySelective(TFloodRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKey(TFloodRoleResource record);
}