package com.hq.flood.dao.generate;

import com.hq.flood.entity.generate.TFloodResource;
import com.hq.flood.entity.generate.TFloodResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFloodResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    long countByExample(TFloodResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByExample(TFloodResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insert(TFloodResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insertSelective(TFloodResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodResource> selectByExampleWithRowbounds(TFloodResourceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodResource> selectByExample(TFloodResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    TFloodResource selectByPrimaryKey(String resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFloodResource record, @Param("example") TFloodResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExample(@Param("record") TFloodResource record, @Param("example") TFloodResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKeySelective(TFloodResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_resource
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKey(TFloodResource record);
}