package com.hq.flood.dao.generate;

import com.hq.flood.entity.generate.TFloodRole;
import com.hq.flood.entity.generate.TFloodRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFloodRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    long countByExample(TFloodRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByExample(TFloodRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insert(TFloodRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insertSelective(TFloodRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodRole> selectByExampleWithRowbounds(TFloodRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodRole> selectByExample(TFloodRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    TFloodRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFloodRole record, @Param("example") TFloodRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExample(@Param("record") TFloodRole record, @Param("example") TFloodRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKeySelective(TFloodRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKey(TFloodRole record);
}