package com.hq.flood.dao.generate;

import com.hq.flood.entity.generate.TFloodOperRole;
import com.hq.flood.entity.generate.TFloodOperRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TFloodOperRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    long countByExample(TFloodOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByExample(TFloodOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insert(TFloodOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int insertSelective(TFloodOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodOperRole> selectByExampleWithRowbounds(TFloodOperRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    List<TFloodOperRole> selectByExample(TFloodOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    TFloodOperRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") TFloodOperRole record, @Param("example") TFloodOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByExample(@Param("record") TFloodOperRole record, @Param("example") TFloodOperRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKeySelective(TFloodOperRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flood_oper_role
     *
     * @mbg.generated Wed Feb 15 23:13:34 CST 2017
     */
    int updateByPrimaryKey(TFloodOperRole record);
}